### ISSUE TITLE
De embedding multi frequency 2port network touchstone files

### ISSUE THREAD

**Issue by Argonghost** [scikit-rf/scikit-rf#1043]
Hi!

Id like to de-embed two files from each other that are touchstone based, however the s parameters are 3d matrices i.e (2001,2,2) in this form. Using scikit rf i managed to get a result with dimension of (1,2,2) which means at single frequency point, how can i do it accross the whole frequency spectrum.

Sincerely

**Comment by FranzForstmayr** [comment]
@Argonghost 
Did you find a working solution?
