### ISSUE TITLE
Weird result when de-embedding bad transmission line using IEEEP370_SE_ZC_2XThru

### ISSUE THREAD

**Issue by shengfang2017** [scikit-rf/scikit-rf#1131]
Hi guys,

I got weird result when de-embedding a bad transmission line. If changes to good transmission line, the result is reasonable and close to DUT. 

This is the fixture TDR result, it has big capacitor at the very front.  
![image](https://github.com/user-attachments/assets/c0ee7d30-d322-439a-aae6-c7f62042f076)

After de-embedding, the DUT TDR of ZC results: 

![image](https://github.com/user-attachments/assets/41894ea7-3fc6-48b8-8e1b-c8c4080813c3)

S-parameter results are:

![image](https://github.com/user-attachments/assets/c8cd092a-f732-4fa2-ab9f-f4ce55a2be72)

NZC can get a roughly close result to dut, but ZC is nowhere close to it,  gets positive result in S11.

Here is the s2p files for 2XThru, DUT, and FDF. 
[s2p.zip](https://github.com/user-attachments/files/16352884/s2p.zip)

**Comment by shengfang2017** [comment]
forgot to pin @mhuser, I believe you are the expert of IEEEP370

**Comment by mhuser** [comment]
Hello @shengfang2017 

Thank you for your report and dataset.

I do not know if I am an expert, but looking to your data I am not surprised ZC does not works. There is a key difference between `NZC` and `ZC`, it does not just correct for the impedance.

- `NZC` S-parameters bisection is done by time gating S11 and S22, taking the
    proper square root of the S21 corrected by return loss, and remixing the
    parameters according to the fixture signal flow graph. This method gives
    crude results but is robust.
- `ZC` computes the length of the fixtures by halving the length of
    2x-Thru and also extract the propagation constant gamma from it. It then peels iteratively FIX-DUT-FIX by determining start
    impedance in time-domain, deembedding a one time sample long transmission
    line of this impedance and loop again until the fixtures mimic FIX-DUT-FIX
    sides impedance profile.

Not all fixtures are properly modeled by a cascade of short transmission lines with different impedance and the same propagation constant gamma, especially when Z is far from reference and gamma vary along the path. This may led `ZC` to gives terrible results.

In other words, `ZC` works only with a **good transmission line**. Your 2xThru fail most of the IEEE370 fixture electrical requirement, thus deembedding it may get you in troubles.

Here we can test it by passing also 2xThru both as 2xThru and FIX-DUT-FIX and test the residuals of deembedding the fixtures from it which should be 0 dB and 0 deg.

![image](https://github.com/user-attachments/assets/97717c76-17f0-4be0-a2c3-f8ea30818a80)
 
Variation of results depending of determined gamma:
```Python
dm = IEEEP370_SE_ZC_2xThru(dummy_2xthru = s2xthru, dummy_fix_dut_fix = s2xthru,
                        bandwidth_limit = 0, verbose = True, NRP_enable = False, leadin = 0)
```
![image](https://github.com/user-attachments/assets/bcde459f-f0ce-492e-971a-8d209100739e)
![image](https://github.com/user-attachments/assets/ed18e8f8-1c83-4129-a38b-4b7850c9c543)
![image](https://github.com/user-attachments/assets/0cb02b35-efe5-4b2f-9c78-1c7372aed0e3)

```Python
dm = IEEEP370_SE_ZC_2xThru(dummy_2xthru = s2xthru, dummy_fix_dut_fix = s2xthru,
                        bandwidth_limit = 21e9, verbose = True, NRP_enable = False, leadin = 0)
```
![image](https://github.com/user-attachments/assets/fb44601f-39a8-428c-b165-d9ccdc44f296)
![image](https://github.com/user-attachments/assets/69df8ebe-778d-4e81-a5df-22e78e363d58)
![image](https://github.com/user-attachments/assets/21f75c4c-65cb-42d3-8b57-0559d87b4571)

**Comment by mhuser** [comment]
@shengfang2017 
Can you share more details about how is the bad transmission line made?

**Comment by mhuser** [comment]
Removing some of the fixture in the middle seems to enhance the results. Is the line made of multiple boards connected or it is just aliasing in the time domain?
```Python
dm = IEEEP370_SE_ZC_2xThru(dummy_2xthru = s2xthru, dummy_fix_dut_fix = s2xthru, pullback1 = 18, pullback2 = 18,
                        bandwidth_limit = 40e9, verbose = False, NRP_enable = False, leadin = 0)
```

![image](https://github.com/user-attachments/assets/88fd02e2-b59d-45aa-8bc2-a91ecd5d1b8d)

**Comment by shengfang2017** [comment]
Hi @mhuser, thanks for the detail explanation. I see the problem now. The big cap is caused by an unskilled PCB layout. 

Here is the top layer metal of brd file in Allegro, everything looks good: 
![image](https://github.com/user-attachments/assets/9bcf5084-bb17-4239-8208-4d382f1f5c55)

Turning on Inner 2 etch shows where the mistake is.  You can clearly see the underfill on inner 2 GND under where the connector resides on the 2 experiment lines
![image](https://github.com/user-attachments/assets/3e286e31-2022-4981-97d2-3f5565156d42)

**Comment by mhuser** [comment]
Oops. Thank you for these insights!

I am adding the final touch to #1114 With this PR you will be able to plot the 2x-Thru against IEEE 370 limit lines and see the gamma determination in ZC through `verbose = True`.

**Comment by shengfang2017** [comment]
Thanks @mhuser, it is really helpful!

**Comment by mhuser** [comment]
You are welcome @shengfang2017 
An example of how to use the new methods to plot fixture electrical requirements can be found in the notebook:
https://scikit-rf.readthedocs.io/en/latest/examples/networktheory/IEEEP370%20Deembedding.html

It is available on the master branch until the next scikit-rf release.
I close this issue as of now, but feel free to write again in case of need.
