### ISSUE TITLE
Touchstone 2.0 format does not seem to work for [Matrix Format] Upper

### ISSUE THREAD

**Issue by ASLOBEAR** [scikit-rf/scikit-rf#1146]
Thank you for reporting a bug! To help us understanding the issue and how to reproduce it, please fill the following sections as best as you can.

**Describe the bug**
When a touchstone v2.0 (.ts) file with [Matrix Format] Upper (as created from Ansys SIwave) is used to instantiate a Network, an UnpicklingError occurs. I open in Ansys Network Explorer tool and reexport the data, which now shows [Matrix Format] Full and the network object is correctly created with this file.

**Data**
At this time I am not able to provide a file for test

**System**
 - OS: Windows 10
 - scikit-rf version 1.2

**Comment by jhillairet** [comment]
@ASLOBEAR , any chance you could provide faulty file at some time? 

ping @Samuelopez-ansys

**Comment by Samuelopez-ansys** [comment]
Hi @ASLOBEAR ,

I have exported a .ts file from SIwave.
[ts_file.zip](https://github.com/user-attachments/files/16519468/ts_file.zip)

Then I used PyAEDT to load the file:

from pyaedt.generic.touchstone_parser import read_touchstone

data = read_touchstone(r"C:\Users\slopez\Downloads\sweep_LDCWXG.ts")

data.plot_return_losses()

This method returns an object of the class TouchstoneData, which inherits rf.Network class.

![image](https://github.com/user-attachments/assets/e984e2bb-f320-4b1c-8ee8-5770b03e697e)

If it does not work for you, please share the file.

**Comment by jhillairet** [comment]
@Samuelopez-ansys is PyAEDT using a different Touchstone parser than scikit-rf's ?

**Comment by Samuelopez-ansys** [comment]
@jhillairet For now this is the main parser, here is the code:

https://github.com/ansys/pyaedt/blob/main/pyaedt/generic/touchstone_parser.py#L72

There is another option that is using SPSIM, 

```
from pyaedt.generic.spisim import SpiSim

spisim = SpiSim(r"C:\Users\slopez\Downloads\sweep_LDCWXG.ts")
```

For now we have implemented only COM and ERL computation, but it has much more features.

You can find an example here:
https://aedt.docs.pyansys.com/version/stable/examples/07-Circuit/Virtual_Compliance.html#sphx-glr-examples-07-circuit-virtual-compliance-py

And the source code:
https://github.com/ansys/pyaedt/blob/main/pyaedt/generic/spisim.py

More about SPISIM:
https://www.spisim.com/

@ASLOBEAR

**Comment by Samuelopez-ansys** [comment]
@ASLOBEAR  Sorry, what is this format?

**Comment by Samuelopez-ansys** [comment]
Hi, 

I am using SIwave 2024R1, and the default output format is sNp, in this case s4p:

![image](https://github.com/user-attachments/assets/3b94f5da-28aa-4153-89cd-c214d4b3bb1c)


To export the .ts file, I have right click in the results: Export to Network Data Explorer
![image](https://github.com/user-attachments/assets/bb90092e-641e-48e9-a5f0-15f1f29c5bf2)

And then save as .ts:

![image](https://github.com/user-attachments/assets/33c46e51-be84-4b4d-add7-bbc0d8e9b4b7)

**Comment by Samuelopez-ansys** [comment]
@ASLOBEAR You are right. When there is a mismatch, the .ts from SIwave is different than the one from the network data explorer (which you could use as a workaround).
[ts_file_compare.zip](https://github.com/user-attachments/files/16530808/ts_file_compare.zip)


@jhillairet Please could you check both files? This is the same result, but the ¨SIwave" one is directly exported by the tool. The second one is exported from the network data explorer.

If @ASLOBEAR think it is a bug, please submit a support case in the Ansys customer portal.

**Comment by FranzForstmayr** [comment]
> I put together a very basic microstrip sim and let the tool export the touchstone with the checkbox at the bottom of the SYZ sim setup. This file exhibits the issues I describe. I have not yet tried to parse the file with pyansys as Samuel suggests [SIwave_project1.zip](https://github.com/user-attachments/files/16529962/SIwave_project1.zip)

I can reproduce the issue, I'll try to create a fix.

**Comment by FranzForstmayr** [comment]
> @Samuelopez-ansys no, I just think it needs to be looked at on the skrf side. I saw a [reddit post](https://www.reddit.com/r/rfelectronics/comments/13pi2pw/examples_of_touchstone_v20_files/) looking for touchstone 2.0 examples for testing with this repository; my understanding is TS2.0 is a new feature and just needs more input files for working out wrinkles.

I did a rewrite of the parser a few months, however the reddit post was not directly related to it. I tested the parser against the test snippets from the standard basically.

**Comment by FranzForstmayr** [comment]
@ASLOBEAR thanks for the report!
@Samuelopez-ansys thanks for the support!

**Comment by jhillairet** [comment]
Thank you @FranzForstmayr for this very quick fix!

**Comment by FranzForstmayr** [comment]
@ASLOBEAR if you have valid ts2 mixed mode data I'm happy to test against the parser.
The only example I (or anyone) used for now is from the touchstone specification, which is not very descriptive.

While thinking about this I stumbled accross a small issue. So best continue in #1150 about mixed mode data.
