### ISSUE TITLE
Missing dependency `typing extensions`

### ISSUE THREAD

**Issue by TM90** [scikit-rf/scikit-rf#1169]
Hello,

skrf/circuit.py imports `typing_extentions` since `1.3`

This seems not to be in the dependencies in pyproject.toml, resulting in `ModuleNotFoundError` for fresh environments.

Best regards

Tobias

**Comment by FranzForstmayr** [comment]
Thanks for the report!

Strange that this wasn't found in CI, which version are you using?

As a quick workaround just install `typing_extensions` by `pip install typing_extensions` in your environment.
