### ISSUE TITLE
pna_csv_2_ntwks3() Function Converts Frequency Units without Applying to Network

### ISSUE THREAD

**Issue by nicolerburg** [scikit-rf/scikit-rf#1177]
**Describe the bug**
When using the function read_all_csv() or pna_csv_2_ntwks3() to read data collected from a VNA, the function converts the numerical value of the frequency range to GHz, but doesn't seem to apply the unit change to the Network object so the frequency range is incorrect.

**To Reproduce**
Say I have a folder of switch terms saved as .csv files in dB/deg format with frequency range 300000.0 -18000000000.0 Hz

```
switch_terms_csv = rf.read_all_csv('switch_terms')
print(switch_terms_csv)
```
The output looks something like 
{'forward': 2-Port Network: 'forward',  0.0003-18.0 Hz, 1001 pts, z0=[50.+0.j 50.+0.j], ... }

As you can see, scikit-rf believes the Network frequency range is 0.0001-18.0Hz rather than GHz.

**Expected behavior**
I would expect that either the Network returns a frequency range actually in GHz or the function pna_csv_2_ntwks3() does not convert to GHz.

**Data**
[forward.csv](https://github.com/user-attachments/files/17076131/forward.csv)
Here is the .csv for the forward switch term that is an example file which has this issue after being read by pna_csv_ntwks3().

**Screenshots**
<img width="864" alt="switch_term_bug" src="https://github.com/user-attachments/assets/fa935365-f44a-4913-8933-78ef0297b411">
Screenshot with example of manually fixing frequency range.

**System**
 - OS: Windows 10
 - scikit-rf version: 1.3.0

**Comment by jhillairet** [comment]
Dea @nicolerburg ,
Thank you for submitting the issue. I confirm. This seems to be due to division by 1e9 in `pna_csv_2_ntwks3`, as data are expected in GHz.

As a temporary workaround, I suggest to modify the frequency object to rescale the frequency:

```python
switch_terms_csv = rf.read_all_csv('switch_terms')

print(switch_terms_csv['forward'].frequency)

new_freq = rf.Frequency.from_f(switch_terms_csv['forward'].f * 1e9)
switch_terms_csv['forward'].frequency = new_freq

print(switch_terms_csv['forward'].frequency) 
```
