### ISSUE TITLE
Documentation for most releases missing

### ISSUE THREAD

**Issue by mxxmxn** [scikit-rf/scikit-rf#1180]
Only the documentation for release v0.23.0 and v0.24.0 is published on Read the Docs.

As far as I know, the missing versions have to be activated first, which can be automated using [this guide](https://docs.readthedocs.io/en/stable/guides/automation-rules.html).

**Comment by jhillairet** [comment]
Thank you @mxxmxn 

I've activated all versions 1.x and 0.3 (so just before 1.0).

In the future, any new version 1.x should be added automatically.
