### ISSUE TITLE
Media.inductor produces nan's for L=0

### ISSUE THREAD

**Issue by gvcallen** [scikit-rf/scikit-rf#1205]
**Describe the bug**
When calling Media's "inductor" function with L=0, the resulting s-parameters are NaN due to divide-by-zero.

**To Reproduce**
```
import skrf as rf
from skrf.media import DefinedGammaZ0

frequency = rf.Frequency(10.0, 10.0, 1, 'MHz')
inductor = DefinedGammaZ0(frequency=frequency).inductor(0)
print(inductor.s)
```

**Expected behavior**
An equivalent "thru" set of S-parameters should be returned. This is consistent with the "capacitor" function, which correctly returns an open.

**Additional context**
I believe this is useful in that it takes some load off of the caller. In my case, I am running an optimization, and want the optimizer to decide whether or not an inductor should be present. Currently, I have to add an explicit check in my middleware code if L==0 and replace the circuit with a thru.

I tried implementing this in scikit-rf but ran into a few issues as to what the ideal implementation is, even though it is quite simple to do with some if conditions, however the main issues lie in both the fact that the caller can pass an array for L, and that you cannot exactly specify a "thru" in y-parameters, resulting in issues when trying to set only certain elements of result.y

**Comment by Asachoo** [comment]
Similarly, should we consider expanding our scope to include components such as `Resistors`, `Capacitors`, and others?
If the input is detected to be zero (which can be effectively checked using `np.allclose()` method), should we directly return the theoretical equivalent of the component? For instance, as you mentioned a `0H Inductor()` would be represented as a 'thru'.

**Comment by Asachoo** [comment]
Thanks, @mhuser. It's true that writing the S-Parameters directly gives more flexibility than converting through the Y-parameters. I'll working on providing explicit S-parameter expressions for both `resistor()` and `capacitor()`.

**Comment by mhuser** [comment]
Unfortunately, with the `capacitor()`

$$Z = \frac{1}{j \omega C}$$

which would cause the division by 0 issue again!
There maybe the Y-parameter formulation is good to keep.

**Comment by Ttl** [comment]
The whole S-parameter definition breaks down if port impedance is zero so there's no reason to worry about it.

**Comment by gvcallen** [comment]
Thanks everyone for the very fast response on this.
