### ISSUE TITLE
Can't install with Python3.6 on Anaconda

### ISSUE THREAD

**Issue by kemiktau** [scikit-rf/scikit-rf#133]
Here is the error I get:
UnsatisfiableError:
The following specifications were found to be in conflict:
- python ==3.6.1
- scikit-rf -> python 2.7*
Use "conda info " to see the dependencies for each package.

**Comment by arsenovic** [comment]
what channel are you installing from? anaconda, conda-forge, or scikit-rf?

**Comment by kemiktau** [comment]
Anaconda.

I had Python 3.6 and when I tried to install scikit-rf on anaconda, I got he above error. I downgraded Python to 3.5 and tried again and installation worked. Now, when I try to upgrade to my Python to 3.6, I, obviously, get the same error.

**Comment by arsenovic** [comment]
try to install from scikit-rf channel 

conda install scikit-rf -c scikit-rf

**Comment by kemiktau** [comment]
Works. Thank you
