### ISSUE TITLE
deembeding of multiport device

### ISSUE THREAD

**Issue by razvanc1** [scikit-rf/scikit-rf#152]
I like much to use scikit-rf for deembeding a multiport ( 10 – 20 ports) device.
I have , let see s11p file and corresponding 11  s2p files, for each trace. 
Based on manual I tested successfully , deembeding for a 2 port device but I am wondering if you can help me with my problem.
I attached here my script for 2 port device
import skrf as rf
#import matplotlib.pyplot as plt
#%matplotlib inline
from pylab import *
rf.stylely()
from skrf.data import ring_slot
#ring_slot = rf.Network('data/ring slot.s2p')

import os
#touchstone_file = os.path.join(rf.data.pwd,’ring slot.s2p’)

touchstone_file = '/test/Bandpass Filter.s2p'
touchstone_file2 = '/test/3 dB Pad R.s2p'
ring_slot = rf.Network(touchstone_file)
ring_slot2 = rf.Network(touchstone_file2)
ring_slot.plot_s_db(m=0,n=1)
ring_slot2.plot_s_db(m=0,n=1)
#ring_slot.plot_s_smith()
t1= rf.Network.a_db

figure()
ring_slot.plot_s_db(m=0,n=0)
ring_slot2.plot_s_db(m=0,n=0)

figure()
ring_slot.plot_s_db(m=1,n=0)
ring_slot2.plot_s_db(m=1,n=0)

deemb1 = ring_slot.inv ** ring_slot2
deemb2 = ring_slot2.inv ** ring_slot

figure()
ring_slot.plot_s_db(m=1,n=0, label = 'S21 measured')
#ring_slot2.plot_s_db(m=1,n=0)
deemb1.plot_s_db(m=1,n=0, label = 'S21 deembeded')
#deemb2.plot_s_db(m=1,n=0)

figure()
ring_slot.plot_s_db(m=1,n=1, label = 'S22 measured')
#ring_slot2.plot_s_db(m=1,n=0)
deemb1.plot_s_db(m=1,n=1, label = 'S22 deembeded')
#deemb2.plot_s_db(m=1,n=0)

**Comment by arsenovic** [comment]
hi! this type of question is better addressed to the scikit-rf mailing list, 

https://groups.google.com/forum/#!forum/scikit-rf
