### ISSUE TITLE
Rise time for TDR?

### ISSUE THREAD

**Issue by doctor-yes** [scikit-rf/scikit-rf#220]
In the TDR measurement vs simulation example (https://scikit-rf.readthedocs.io/en/latest/examples/networktheory/Time%20domain%20reflectometry,%20measurement%20vs%20simulation.html), there seems no way to set the rise time of the incident step. I checked the document and doesn't look like we can set that for step_response either. In a real TDR measurement the Trise will be set (to 50ps etc). Is there a way to simulate using different Trise in scikit-rf? Thanks.

**Comment by mhuser** [comment]
Dear @doctor-yes,

In the related example, the network is simulated in the frequency-domain and the time-domain results are obtained by computing the inverse of the fast Fourier transform.

This is the same behaviour as TDR measurement with a vector network analyser (which stimulate the network with sines waves of varying frequencies), but this is not "physically" the same as a time domain device which really send a step with a certain rise time. For this reason, there is no rise-time setting.

However, the results should be close in both cases. The "rise time" equivalent with the inverse Fourier transform computation is related to the frequency  span of the studied network and is usually approximated by 0.35/Fmax, where Fmax is the upper frequency of a linear harmonic sweep.

[see page 4 as an illustration](http://mpd.southwestmicrowave.com/showImage.php?image=1124&name=Utilizing%20Time%20Domain%20(TDR)%20Test%20Methods%20For%20Maximizing%20Microwave%20Board%20Performance)

Tuning the frequency axis of the networks could be achieve to simulate the equivalent of different rise time.

**Comment by doctor-yes** [comment]
Point well made. That said we just need to do slicing (http://scikit-rf.readthedocs.io/en/latest/tutorials/Networks.html#Slicing) to remove unneeded frequency points before calling the plot_z_time_step or step_response? 

BTW, what is the difference between plot_z_time_step or step_response? Is the data processed in the same way and just one create a plot one doesn't? Thanks.

**Comment by mhuser** [comment]
Great idea!
Let's say there is a measured S-parameter dataset from 10 MHz to 10 GHz with 10 MHz step (harmonic sweep, 1000 points), the equivalent rise time would be 0.35/10GHz = 35ps.
If now these data are sliced to take only values from 10 MHz to 5 GHz (harmonic sweep, 500 points), the equivalent rise time would become 70ps.

`plot_z_time_step` call internally `step_response` and convert the resulting reflexion coefficients into ohms based on the characteristic impedance. 
This happens [in this function](http://scikit-rf.readthedocs.io/en/latest/_modules/skrf/plotting.html#plot_func). Unfortunately, this part of the code is a bit obfuscated because of the way plotting functions are automatically generated.

**Comment by doctor-yes** [comment]
understood. I don't see the plot_z_time_step function in your link... Looks like I need to convert reflexion coefficients into ohms myself if I want to get the result in ohms anyway? (I will not be able to get such data out of plot_z_time_step function?). Thanks.

**Comment by mhuser** [comment]
Sorry, there was an issue with the anchor in the link.
Here follow the code snippet that convert the reflexion coefficient into impedance, with x the time axis and y the impedance axis. The characteristic impedance z0 has to be defined :

```
xlabel = 'Time (ns)'
x, y = self.step_response(pad=pad, window=window)
# default is reflexion coefficient axis
if attribute[0].lower() == 'z':
    # if they want impedance axis, give it to them
    y_label = 'Z (ohm)'
    y[x ==  1.] =  1. + 1e-12  # solve numerical singularity
    y[x == -1.] = -1. + 1e-12  # solve numerical singularity
    y = z0 * (1+y) / (1-y)
```
I am not sure if there is a possibility to get directly the plot_z... function results.
These TDR functionnalities are a bit experimental and of course could be enhanced.

**Comment by Vinc0110** [comment]
This issue is rather old and I don't see a bug or anything here that requires fixing. I think it was mainly a user question, maybe a feature request (reply was missing), so I'm going to close this issue. Please complain and I will reopen it.
