### ISSUE TITLE
Getting warning/error that Network has no member plot_s_db or plot_s_smith

### ISSUE THREAD

**Issue by markitman2** [scikit-rf/scikit-rf#230]
Using VS code for IDE. Following is the code

import pylab
import skrf as rf
from skrf.data import ring_slot

# create a Network type from a touchstone file of a horn antenna
# ring_slot= rf.Network(ring_slot)

# plot magnitude (in db) of S11
pylab.figure(1)
pylab.title('Return Loss (Mag)')
ring_slot.plot_s_db(m=0,n=0) # m,n are S-Matrix indices

# show the plots
pylab.show()

**Comment by arsenovic** [comment]
i cant really see your text easily ,
but his line is not needed
    ring_slot= rf.Network(ring_slot)
