### ISSUE TITLE
warning after upgrade to Matplotlib V3.0.1

### ISSUE THREAD

**Issue by alexatadi** [scikit-rf/scikit-rf#233]
Met below warning when work with new matplotlib version 3.0.1, no this warning in previous version

> i:\sci\Anaconda3\lib\site-packages\matplotlib\__init__.py:886: MatplotlibDeprecationWarning: 
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))

To reproduce:

> import skrf as rf
rf.stylely()

**Comment by arsenovic** [comment]
that doesnt seem related to scikit-rf.
