### ISSUE TITLE
skrf.network.inv description is not clear

### ISSUE THREAD

**Issue by alexpacini** [scikit-rf/scikit-rf#235]
In the description I read:

    Calculates 'inverse' s-parameter matrix, used for de-embedding

    This is not literally the inverse of the s-parameter matrix. Instead, it
    is defined such that the inverse of the s-matrix cascaded
    with itself is unity.

I am not sure it is right, since a unity matrix has ones on the diagonal and means total reflection for each port.

Probably should be rephrased as:

    Calculates 'inverse' s-parameter matrix, used for de-embedding

    This is not literally the inverse of the s-parameter matrix. Instead, it
    is defined such that the inverse of the s-matrix cascaded
    with itself is a unity scattering transfer parameter (T) matrix.

See [this appnote from Keysight](http://literature.cdn.keysight.com/litweb/pdf/5980-2784EN.pdf)

The following is an example in a Iphthon notebook

![screenshot_20181123-230120-01](https://user-images.githubusercontent.com/2548281/48962201-b06d5480-ef74-11e8-8101-b98b3e7590a4.jpeg)
![screenshot_20181123-230124-02](https://user-images.githubusercontent.com/2548281/48962203-b6633580-ef74-11e8-8209-644c68b9d3a4.jpeg)
So the behavior of Network.inv is fine, but the description is not clear.

The other issue is on its definition for a N-port. The s2t is defined only for 2N ports.
Anyway I struggle to visualize the T matrix for a 2N port with N greater than one.

**Comment by mhuser** [comment]
@alexpacini the `Network.inv` is implemented for 2N-port network considering an equal number of left-input and right-output, in such a way T-matrix can always be cascaded.
An example would be modelling a differential pair for de-embedding. This would results in a 4-port network that could eventually by removed from a measurement.

**Comment by alexpacini** [comment]
Ok, this make sense.
Therefore all the odd ports on one side and the even on the others?
Maybe a math representation of the T matrix in the docs would be helpful.
