### ISSUE TITLE
Filter responses of a bandpass, bandstop, highpass, lowpass

### ISSUE THREAD

**Issue by DavidLutton** [scikit-rf/scikit-rf#239]
I have access to a number of filters without details, having response profiling tools would be useful to process them.
[I have written a function to return the 3dB points of a bandpass filter](https://gist.github.com/DavidLutton/328bc003c7632c541c8f68d457d419ee)

Is this suitable concept for inclusion in this project?

In this example the data export did something odd, shows as a bandpass filter with gain 
![if filter](https://user-images.githubusercontent.com/1688143/50547651-026d5e00-0c36-11e9-842c-cf8774bfb3e7.png)

**Comment by DavidLutton** [comment]
For highpass, just changing the source data and plot title
![highpass](https://user-images.githubusercontent.com/1688143/50549277-d1028b80-0c51-11e9-9223-ab85f871cdb2.png)

For lowpass, just changing the source data and plot title
![lowpass](https://user-images.githubusercontent.com/1688143/50549347-35721a80-0c53-11e9-96dd-ff34497d28de.png)

**Comment by arsenovic** [comment]
david, 
   not sure why i didnt respond to this. i think this would make a great example notebook. 

to make it a function i think you would will need  more general parameters like  3db-> any db, dont hardcode mhz, etc. but i like your idea, and it works great.

**Comment by dl1chb** [comment]
Also estimating the filter's order would be nice (which could lead to estimate the poles and zeros ;-)).

**Comment by DavidLutton** [comment]
- [x] Work on this issue in JupterLab, which is easier to iterate/retry
- [x] Get access to a VNA and collect samples of different filters: Band Pass, Low Pass, High Pass 
- [x] Removed the handling frequency parts and changed to working with data points
- [x] Fix incorrect selection of regions that don't fulfil the intended criteria (may need tuning)
- [x] ndB point to ndB (arbitrary) and optional offset
- [ ] Update the gist and samples
- [ ] Tag regions with the criteria that they were identified by

`filter_region(net.s11, 0, -3, offset=np.max(net.s11.s_db))`
`filter_region(net.s11, -3, -60, offset=np.max(net.s11.s_db))`
![image](https://user-images.githubusercontent.com/1688143/55674314-05b65c80-58ab-11e9-8b1f-a848a1c2bcc0.png)
`filter_region(net.s11, 0, -3, offset=np.max(net.s11.s_db))`
`filter_region(net.s11, -3, -90, offset=np.max(net.s11.s_db))` 
![image](https://user-images.githubusercontent.com/1688143/55674691-d35b2e00-58af-11e9-80bd-9112fbc78a69.png)

**Comment by jhillairet** [comment]
Dear @DavidLutton, is your function been updated/completed?

**Comment by jhillairet** [comment]
Closing because no news. You can reopen if necessary.
