### ISSUE TITLE
Minor: v0.14.9 tag not in master branch

### ISSUE THREAD

**Issue by beuerle** [scikit-rf/scikit-rf#242]
This is a minor issue, but it confuses `git describe`:

The `v0.14.9` tag is not in the master branch, and thus `git describe` points to the latest `v.0.18` release.

```bash
$ git describe
v0.14.8-54-g66f2f3a
```

**Comment by arsenovic** [comment]
thanks for pointing this out, not sure how this  happened,  ill try to fix
