### ISSUE TITLE
Warning  because of deprecated art of module importing

### ISSUE THREAD

**Issue by bessembaccoucherohde** [scikit-rf/scikit-rf#258]
![Capture](https://user-images.githubusercontent.com/50130704/56942996-c8e22c00-6b1d-11e9-833a-34cb55f59ef1.PNG)

**Comment by jhillairet** [comment]
Could you precise which version of python and which circumstances you see these warning?

**Comment by bessembaccoucherohde** [comment]
3.7

**Comment by jhillairet** [comment]
I'm also using Python 3.7 (3.7.3) and I don't have this warning. How did you install skrf (conda, pip, github) ?

**Comment by bessembaccoucherohde** [comment]
pip3, 
this kind of importing will stop working from 3.8

**Comment by jhillairet** [comment]
Please let us know if the problem still exists by updating/installing new versions from pip or conda (preferred) by openning new issue.
