### ISSUE TITLE
apply_cal cannot be applied to NetworkSet

### ISSUE THREAD

**Issue by cweickhmann** [scikit-rf/scikit-rf#260]
Is there a reason apply_cal (for instance in skrf.calibration.TRL) cannot be applied to a NetworkSet?

MWE:
```python
import skrf as rf

trl = rf.TRL([thru, refl, line])

net = rf.Network("somefile.s2p")
net_set = rf.NetworkSet.from_dir("./some_measurements", name="Some Measurement")

cal_net = trl.apply_cal(net)   # <-- this works
cal_net_set = trl.apply_cal(net_set)   # <-- this fails

# Work around:
cal_net_set = [trl.apply_cal(n) for n in net_set]
```

The problem with this work around is that a property like "name" in this case is not saved.

**Comment by jhillairet** [comment]
I don't think there is a specific reason it could not be applied. This is a good idea.

**Comment by arsenovic** [comment]
yes this would be welcome. there are methods like `apply_cal_to_list`, and `apply_cal_to_all_in_dir`

**Comment by cweickhmann** [comment]
We often have the case that a bunch of measurements is in a NetworkSet for work-flow reasons.
@arsenovic, you're the first to point this out. Am I blind or are those functions not documented? (It's probably the first ...)
If I have time, I'll try to write an implementation.

**Comment by arsenovic** [comment]
https://scikit-rf.readthedocs.io/en/latest/api/calibration/generated/skrf.calibration.calibration.Calibration.html#skrf.calibration.calibration.Calibration

**Comment by arsenovic** [comment]
i think you can just write a little  method for your use, something like ,

`my_cal.apply_cal_to_ns = lambda x: rf.NS(my_cal.apply_cal_to_list(x))`

if you want to use it in the future or have stable scripts then its better to add it to skrf.

**Comment by cweickhmann** [comment]
Thanks, @arsenovic!
As mentioned above, the problem I have with going via a list of Networks is losing the name attribute.
Fork is underway ;-)
