### ISSUE TITLE
Version nudge?

### ISSUE THREAD

**Issue by TL-SjoerdOptLand** [scikit-rf/scikit-rf#262]
Shouldn't this version be updated to be at least 0.14.9? Is it possible/useful to include a 'git' postfix to the version for non-released versions?

https://github.com/scikit-rf/scikit-rf/blob/a2442ca3a830ec7210ac0c0e06af0c533d8224c7/skrf/__init__.py#L9

**Comment by arsenovic** [comment]
yes, and yes.

**Comment by TL-SjoerdOptLand** [comment]
From https://packaging.python.org/guides/single-sourcing-package-version/ , I get the impression that https://pypi.org/project/setuptools-scm/ (with the git plugin) can unambiguously take the version number from the Gitlab tag/commit. Once this is set-up, you shouldn't have to worry about this anymore.
