### ISSUE TITLE
Test documentation

### ISSUE THREAD

**Issue by climbit** [scikit-rf/scikit-rf#271]
Hi all,

I don't get the tests running on my local machine. 
I use ubuntu and pycharm as IDE.
Within the virtual environments for python2.7 and python 3.6 I installed the following:
```
pip install -e local/skrf/dir
pip install nose
```
Is it possible to write an instruction, how to setup the tests, in the development page or in the documentation?
I just saw that the travis ci uses conda. Do I have to install everything via conda for the tests?

Other than that, the link in the development page seems to be outdated as the numpy/scipy project no longer use nose (as the linked page told me).

best regards,
Daniel

**Comment by jhillairet** [comment]
You can run the tests using nose, for instance by running the following commands in the scikit-rf root directory (cloned from github for instance):
```
cd scikit-rf
nosetests skrf -c nose.cfg
``` 
(which also requires the [nose-exclude](https://pypi.org/project/nose-exclude/) package to be installed, in addition to the packages listed in `requirement.txt`  .)
