### ISSUE TITLE
Question: Antenna gain calculation

### ISSUE THREAD

**Issue by ivlis** [scikit-rf/scikit-rf#287]
The common technique to measure realized antenna gain is to measure S21 of the antenna under test (AUT) and measure S21 of a known reference antenna in the same environment. That's the AUT gain is

Gain_AUT [dBi] = Gain_REF [dBi] - S21_REF [dB] + S21_AUT [dB] 

I can easily import REF and AUT antenna measurements into scikit-rf as 2-port networks and then calculate - S21_REF + S21_AUT

For Gain_REF, I have a table with two columns of frequency and Gain in dBi. How can I incorporate this into scikit-rf, so I can use frequency scaling, plotting and all other features of scikit-rf for my gain values?

**Comment by denzchoe** [comment]
There is a dedicated Google Group for this kind of questions.
https://groups.google.com/forum/#!forum/scikit-rf

I suggest you ask it there. This section is mostly for Issues concerning the distribution package.

Btw, the answer to your question: You can create a dummy Network object (from your Gain_REF file) and perform algebra calculations in dB easily once you have it convert to Network Objects.
