### ISSUE TITLE
vna.py: log sweeps with PNA

### ISSUE THREAD

**Issue by AntonGut** [scikit-rf/scikit-rf#29]
Similar to https://github.com/scikit-rf/scikit-rf/issues/15 for different hardware.

In PNA class frequency vector gets generated using f_start/f_stop/f_npoints, which assumes linear sweep. For log sweeps frequency vector will be wrong.

No fix from me just yet since I don't need log sweep ATM. 

An idea for implementation: use first column from CALCulate<cnum>:DATA:SNP:PORTs? reply, possibly inside get_data_snp()

**Comment by DavidLutton** [comment]
For generating log spaced steps [numpy.geomspace — NumPy v1.12 Manual](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.geomspace.html)

`numpy.geomspace(start, stop, num=50, endpoint=True, dtype=None)`
