### ISSUE TITLE
Create New Networks Based on Media Models

### ISSUE THREAD

**Issue by MichaelOld** [scikit-rf/scikit-rf#304]
Hi, 

I am new to skrf and I have been having trouble to create new networks based on media models. For example, if one piece of coaxial cable media is created and I want to generate a two-port S parameter network as if the S parameter network is measured from a VNA. I found that there is no 'synthesize' function to generate a network based a the coaxial cable media. Am I missing some document that I should look at or this kind of operation is not intended in scikit-rf? 

Thank you!

**Comment by MichaelOld** [comment]
For example, I would expect S11 in the following case not being perfected matched. Is there anything I did wrong?
![image](https://user-images.githubusercontent.com/52091862/70282660-7f7d4d80-178c-11ea-89ee-3400d291aba1.png)

**Comment by jhillairet** [comment]
Welcome,

The way you build your line is OK, but here you have built a line which is not terminated (a 2-ports network), such like this :
![2ports](https://user-images.githubusercontent.com/4642848/70338101-95eade00-184c-11ea-81c5-6d73ab77b210.png)

If you want the line to be matched (1-port network), you need to connect to it a matched load. For example like this :
```
matched_line = cable_1_sn ** cable_1.match() 
```

**Comment by jhillairet** [comment]
Dear @MichaelOld, is it OK?

**Comment by MichaelOld** [comment]
Thank you for your replay, @jhillairet 

The S parameter you described is the result of measuring with Z0 same as the transmission line's impedance. But my intention was to get the S parameter as if the transmission line is measured with a 50Ohm VNA. Is there a way to analyze a piece of TL and obtain its S parameter over frequency with respect to a 50Ohm measurement?

regard,
Thanks again!

**Comment by mhuser** [comment]
Dear @MichaelOld,

If I understand properly, your target is to get the same network as if the transmission line has been measured with 50-ohm, well calibrated 2-port VNA.

For this, two solutions exist:
1. Use of the embed feature of media.line (see [here](https://scikit-rf.readthedocs.io/en/latest/api/media/generated/skrf.media.coaxial.Coaxial.line.html#skrf.media.coaxial.Coaxial.line))
2. Explicitly set the port impedance

```
import matplotlib.pyplot as plt
from skrf.frequency import Frequency
from skrf.media import Coaxial

f = Frequency(5e-3,5,1000, 'ghz')
m = Coaxial(f, Dint=1.05e-3, Dout=5e-3, epsilon_r=2.02, tan_delta=0.00022)
tl1 = m.line(120, 'mm', z0 = 50)
tl2 = m.line(120, 'mm', z0 = 50, embed=True)
tl3 = m.thru(z0=50) ** m.line(120, 'mm') ** m.thru(z0=50)

plt.figure()
plt.title('RL Comparison')
tl1.plot_s_db(0,0, marker='^', markevery=10)
tl2.plot_s_db(0,0, marker='o', markevery=10)
tl3.plot_s_db(0,0, marker='x', markevery=10)

plt.savefig('tl-comparison.png')
```
![tl-comparison](https://user-images.githubusercontent.com/8080934/70839414-f9f14180-1e0c-11ea-9c4b-dd1df56500ed.png)

If the impedance of the line is given (e.g. `tl1 = m.line(120, 'mm', z0 = 50)`), then the impedance of the line will be 50 ohm and there will be no mismatch. tl2 implement solution 1 and tl3 solution 2.

**Comment by MichaelOld** [comment]
Hi @mhuser, it look very promising. Thank you so much for your example!
