### ISSUE TITLE
Missing calculation of the simultaneously matching impedances Z1,Z2 of a 2 port network.  

### ISSUE THREAD

**Issue by FournierVincent** [scikit-rf/scikit-rf#314]
formula 
z1=sqrt(z11*DZ/z22) 
z2 = sqrt(z22 *DZ /z11)
DZ=z11*z22-z21*z12

I suppose that the formula can be easily extendend to multiport. 

Very usefull to calculate the minimum losses of a circuit. 
(for an active circuit, the k factor check must be performed)

**Comment by jhillairet** [comment]
They are implemented for a more general case under the name _Active-Parameters,_ such as `z_active` (same for S, Y and SWR): 
https://scikit-rf.readthedocs.io/en/latest/api/generated/skrf.network.Network.z_active.html
in which the excitation can be defined, which is useful for phased arrays for instance. 

OK, the documentation equations is not perfect ;)
