### ISSUE TITLE
SOLT and TwelveTerm Calibration Issues

### ISSUE THREAD

**Issue by bock2911** [scikit-rf/scikit-rf#329]
I am trying to get the SOLT or Twelve Term RF calibration algorithms to work.  However, whenever I put in the data, it always provides me with non-sensical results.  Like S11 and S21 both being close to 0 dB (if not with some gain).  I have made simulated RF data for all of the standards in order to debug, and it always fails.  

Now, it should be noted that the Rf data that I generated has no crosstalk in the errorbox elements, as well as the standards in the model have no crosstalk as well.  

My questions are:
1. what does the note 'flush thru' mean for SOLT cal?
2. i can get it to work with the 8-term cal. Why is that?  
3. for the example on the website for SOLT, does anyone have the touchstone files for the SOLT example?  I cannot find them?  
4. The code I am using is literally a copy and paste from the scikit-rf SOLT example on the website, so i do not think it is my code.

any help would be appreciated.

-Dan

**Comment by arsenovic** [comment]
hi i think this would be better posted to the users mailing list
