### ISSUE TITLE
solve circuit sparameters

### ISSUE THREAD

**Issue by joamatab** [scikit-rf/scikit-rf#333]
Hi!

How can we concatenate solve the Sparameters of a network where we know the Sparameters of the components and the netlist?

For example I'd like to connect the horn antenna and the ring slot from the examples folder

**Comment by jhillairet** [comment]
Hello,

Assuming `ring_slot` is a 2 ports Network and `horn` is a 1 port Network, then the concatenation of both (cascading) is:
`result = ring_slot ** horn` 

You will find more information here:
https://scikit-rf.readthedocs.io/en/latest/tutorials/Networks.html#Cascading-and-De-embedding

Please use the [mailing list ](https://groups.google.com/forum/#!forum/scikit-rf) if you have other questions.
