### ISSUE TITLE
Error in "draw_labels" in rf.plotting.smith for Y-Smith chart (option chart_type='y')

### ISSUE THREAD

**Issue by Gerd-Vandersteen** [scikit-rf/scikit-rf#347]
Hi,

When using the admittance Smith chart with labels using 
>> rf.plotting.smith(chart_type='y', draw_labels=True)
one sees that the labels for the real and imag part of the admittances are incorrect. The real part should go (from left to right from /infty to 0.0, and the imag part on the unit circle goes (clock wise) from \infty j over -j to 0,  +j and back to \infty. 

It should be a point mirroring from the impedance to the admittance smith chart.

**Comment by JAnderson419** [comment]
Hello Gerd-Vandersteen,

Thanks for taking the time to open an issue for the problem you are having. Would you be able to do us a favor and upload a minimal working example so that we can try to reproduce and track down the error? I see this is the first issue opened on your Github account, so if you have any questions don't hesitate to ask.

Cheers,
Jackson

**Comment by Gerd-Vandersteen** [comment]
The following example has a normalized admittance of 2+0.5j and should indicate on the Y-Smith chart as such ...

import matplotlib.pyplot as plt
import numpy as np
import skrf as rf

Y=0.04+0.01j
Z=1/Y
print(Z)

Z0=50
z=Z/Z0
print(z)

y=1/z
print(y)

s=(z-1)/(z+1)
print(s)

rf.plotting.smith(chart_type='y', draw_labels=True)
plt.plot(np.real(s),np.imag(s),'o')
plt.show()

**Comment by jhillairet** [comment]
Thank you for reporting. The example you've indicated generates the following figure : 
![image](https://user-images.githubusercontent.com/4642848/78702573-1871d000-7909-11ea-9799-3dadfac04ad1.png)
It's right that the x-labels should be reverted, like in : 
![image](https://user-images.githubusercontent.com/4642848/78703393-5d4a3680-790a-11ea-9a15-2d5cad2c2ccb.png)

**Comment by Gerd-Vandersteen** [comment]
Dear Julien,

Correct!

Tip: the plot you showed from antenna-theory.com has real valued labels around the unit circle, while as a matter of fact these labels represent the complex value of the admittance. Hence, it is more logical to use the complex values (such as -0.5j) as label on the unit circle.

Best regards,

Gerd

[cid:image002.jpg@01D60D8E.249F11D0]
Prof. dr. ir. Gerd Vandersteen
Building K- Room 430
Pleinlaan 2 – 1050 Brussels – Belgium
T +32 (0)2 629 29 44
M +32 (0)474 21 51 22

**Comment by jhillairet** [comment]
OK, first attempt for correction. I'm not sure to have understoof your Tip. Is it OK?
![Figure_4](https://user-images.githubusercontent.com/4642848/79662942-0586b780-81b5-11ea-91f2-74c59b7c1f2b.png)

**Comment by Gerd-Vandersteen** [comment]
Dear Julier,

The labels are looking fine. The dot is now positioned at 2+0.5j.

Best regards (my students and I are appreciating your effort).

Best regards,

Gerd

**Comment by Gerd-Vandersteen** [comment]
Dear Julier,
The labels are looking fine. The dot is now positioned at 2+0.5j.
Best regards (my students and I are appreciating your effort).
Best regards,
Gerd

[cid:image002.jpg@01D616ED.6DE8EC90]
Prof. dr. ir. Gerd Vandersteen
Building K- Room 430
Pleinlaan 2 – 1050 Brussels – Belgium
T +32 (0)2 629 29 44
M +32 (0)474 21 51 22

**Comment by jhillairet** [comment]
Fixed from #348 . Thanks for reporting!
