### ISSUE TITLE
scikit-rf 2020 Survey Results

### ISSUE THREAD

**Issue by jhillairet** [scikit-rf/scikit-rf#357]
# scikit-rf 2020 Survey Results

## Survey is closed since 24/01/2021 

Results as of 24/01/2021 – 41 responses

[The scikit-rf 2020 survey](https://forms.gle/yioPhwX2bYyyTgy8A) is intended to all the users of this package, in order to determine what are the functionalities used the most and the less, the ones which could be improved or new directions for developments, etc.

I'm posting the results in a new issue in order to be able to copy/paste the images of results and charts. This is also the opportunity to discuss the results (and keep track of this discussion.)

# Part 1 - your usage of scikit-rf
![image](https://user-images.githubusercontent.com/4642848/105643783-33123700-5e92-11eb-8161-6a5ec7a4c406.png)

![image](https://user-images.githubusercontent.com/4642848/105643790-3c9b9f00-5e92-11eb-80f1-33dac5f74f43.png)

context
![image](https://user-images.githubusercontent.com/4642848/105643818-7076c480-5e92-11eb-9f05-ad6dd4c751b0.png)

main domain
![image](https://user-images.githubusercontent.com/4642848/105643824-7b315980-5e92-11eb-9d5e-8156a133f8cd.png)

main use
![image](https://user-images.githubusercontent.com/4642848/105643851-a5831700-5e92-11eb-8a4c-4703cbab1031.png)

OS:
![image](https://user-images.githubusercontent.com/4642848/105643855-ae73e880-5e92-11eb-87c6-936a01d85db6.png)

Python version:
![image](https://user-images.githubusercontent.com/4642848/105643860-b59af680-5e92-11eb-9c38-e1804e1a0635.png)

# Part 2: on scikit-rf functionalities, wish-list and support
scikit-rf objects:
![image](https://user-images.githubusercontent.com/4642848/105643865-be8bc800-5e92-11eb-84ba-2d36032ca70d.png)

Improvements:
![image](https://user-images.githubusercontent.com/4642848/105643874-cb102080-5e92-11eb-9d1f-2481937c59da.png)

**Could you give some details on your previous answer?** 
- Being an intermittent user I tend to forget how to do things so good documentation is crucial.
- Making a simple GUI for circuit setup, evaluation, debug and verification would be extremely helpful in visualizing what you are doing. 
- Better Touchstone file imports - I am importing Touchstone files from CST MWS with some (crude) custom code for header parsing. 
- Interpolation of Networks inside a NetworkSet - For example, my network set is a scan over some variable(s) defined in the Touchstone file header. I am using some (also crude) custom code to project this set onto a regular grid, and to extract Network objects interpolated at arbitrary values of the scan variable(s). Operations like integrating a network set with respect to a scan variable is also doable but currently clumsy.
- There are a lot of hidden features that are not well documented. 
- Better method for constructing combinations of multiports (e.g. 4 port coupler connected to 2 amps to another 4 port coupler for balanced amplifier)
- GUI to visualize Network Sets together with Limit Lines. Eg. I have 100 tests of a filter, and I'm able to visualize a trace of the mean, a trace of the mean +/- 4.5 sigma, and the Limit Lines. The limit lines would be linked to the type of data I'm visualizing, such as S21 db, S11 db, etc.
- I am interested in creating a package that use pydantic as base models to store specifications and results.  The skrf package is the go to parser for Touchstone files for me and I would like to use 
- Would be nice to see more amateur-level documentation on using skrf with a VNA.  Would also be nice to support additional calibration types, and/or structure things so adding new calibrations is easier.
- more integration with pandas and xarray (networkset_to_xarray); import/export networkset to generalized MDIF files
- Better/more numerous examples. more Information around how skrf can be integrated into other modules (matplotlib, especially)
- Markers: Max min search, coupled markers across several curves in 1 fig. 
- Nothing specific comes to mind, but a library of many examples would be quite helpful.   Perhaps the user base could contribute parts of their work and a library could be created.  Seeing how someone else implements things and uses the tool not only is good instruction, but it helps me understand other ways to use the tool.
- Plot implementation is difficult to extend
- More, complete, examples that can be used as patterns for new problems.  Ability to draw a circuit graphically, or import from another tool.  Target users are unlikely to be Python experts - make it less Pythonic!  
- There are a lot of methods and functionalities which are buried deep in the code but not properly documented.
- I think scikit-rf is a great fundamental library, and provides the first step for doing a lot of analyses, but for a lot of users, the next step of putting it into use for an application can be a lot of work, and some end users would probably be willing to pay for a more polished end tool.  My answer below is based on having the fundamental library, but would go up significantly if a more polished end user structure was available
- Want to do real time acquisition with pyqtgraph package, have more documentation on how to add new vector analyser.
- NetworkSet is strangely defined ( a list from a dictionary ). it doesn't inherit calculation methods  from Network. Its __str__ is not a summary. It is only for plotting. It could useful -if properly designed- to support the definition of new items such as a tuner (which has a network collection + other topics. The number of plot methods appearing in the tab completion is far too big and should be grouped under NetworkSet.plots.* . (Otherwise the tab completion is not usable). 
- It is strangely slow in plotting. 
- In my opinion, NetworkSet should be redefined and rewritten
- Network __str__ does not reflect the noise parameters. It should tell at least some info, perhaps the range of NF and the noise freq if different from frequency.  
- Noise parameters should be tested against realistic values : 
- realistic = rn/z0>T0/4/T*(mf.db10_2_mag(nfmin_db)-1)*sq(1+gamma_opt)*(1-sq(s11))/sq(1-gamma_opt*s11).
- The noise contour plots should be available as circles. The actual implementation is far too calculation intensive.
- Single frequency  Networks are very useful in Noise caculations. The __str__ could reflect the single freq by a 75GHz instead of 75-75GHz. 
- Valentino's NF calculation has not been implemented. 
- Tutorials and documentation need some cleaning : the same articles in the main page can be found in the detailed pages. Noise examples are missing. 
- Calibration : Is there anyway to read the internal calfiles from VNA manufacturers so that the switch terms are available. This is necessary for S2P extraction between calplanes. 
- This being said, scikit-RF is a very good and necessary tool. I love it !
- I don't think that a GUI should be part of the core library. I think that the core package should be as light as possible, so it can be used also for live control systems. On this regard, I think improving the performances is also important, ideally using Cython or writing python C extensions (no CFFI or ctypes).
- The plotting extensions should not be part of the core package in my opinion and I never plot using that. I always use matplotlib by itself or pySmithPlot. One interesting add-on would be to split the plotting libs into a util package and also integrate pySmithplot.
- scikit-rf is great!
- Please give more examples about the codes and how it can be used effectively
- I've to write python code to customize what ever graphical desired
- A number of methods are autogenerated and make autocomplete / API difficult. se2gmm I believe is also not working correctly (I believe impedances get messed up). I would move all plotting out of Network and not make matplotlib nor jupyter/ipython a required dependency. 

If commercial
![image](https://user-images.githubusercontent.com/4642848/105643898-f2ff8400-5e92-11eb-8849-f96a9fd88249.png)

other softwares
![image](https://user-images.githubusercontent.com/4642848/105643907-fc88ec00-5e92-11eb-89f2-b226a947b2a0.png)
Largest answers are now ADS, matlab toolbox and own-made code

**Open-Source software needs developers. Developers always appreciate nice comments for their motivation, but they also need food and beers to survive. Would you be inclined to support scikit-rf developers using the github sponsor program?**

![image](https://user-images.githubusercontent.com/4642848/92807806-7e341d80-f3bb-11ea-9122-67cee4d064ee.png)

If you answered yes to the previous question, please have a look the [sponsor github page](https://github.com/scikit-rf/scikit-rf). 

**About one-time sponsoring**: All the sponsoring tiers are monthly, but you can cancel any time you want.

**Comment by iancleary** [comment]
I missed the survey; I've answered some of the questions below and added some discussion as well.

Thank you for compiling the results!

## Context

- Use in a private company

## What is my main use case of scikit-rf?

- "RF Data Post Processing".  

## Active versions

- Python 3.8 on Ubuntu (primarily within a Jupyter Docker container)

## What scikit-rf objects have I used?

- I primarily use the Network object and the skrf.io.general:read_all function.


I contributed to allow the read_all function to the [skrf.io.read_all](https://github.com/scikit-rf/scikit-rf/blob/8e0969c6e34871adbc76981a09f1dce4364b51af/skrf/io/general.py#L217) and am curious if the community thinks that NetworkSet is a better use there.  

We do a lot of analysis of sets of s2p files (across parts or across temperature for the same part), and I haven't ever really looked at NetworkSet.  We primarily use skrf as a parser to create pandas DataFrames and then perform aggregate analysis or create our own plots from there.  Perhaps NetworkSet should be used on that aggregate calculations, especially for the sigma limits or comparisons to limit lines.  Some data vs. plotting separation there.

So we don't generally use the built-in plotting, unless we are investigating networks.  It is very handing in that case for me!

Sponsored
================================

 I appreciate your work. 🎉🚀   Thank you for what you do! 🙂

**Comment by jhillairet** [comment]
Thank you. It is still time to answer the survey. Please follow this link: https://forms.gle/yioPhwX2bYyyTgy8A

**Comment by jhillairet** [comment]
responses updated - 14/06/2020, 23 answers

**Comment by jhillairet** [comment]
Updated the comment on wishes/missing features with the latest responses.

**Comment by scimax** [comment]
> ## Edited (moved answers to survey response).
> * I primarily use the Network object and the skrf.io.general:read_all function.
> 
> I contributed to allow the read_all function to the [skrf.io.read_all](https://github.com/scikit-rf/scikit-rf/blob/8e0969c6e34871adbc76981a09f1dce4364b51af/skrf/io/general.py#L217) and am curious if the community thinks that NetworkSet is a better use there.
> 
> We do a lot of analysis of sets of s2p files (across parts or across temperature for the same part), and I haven't ever really looked at NetworkSet. We primarily use skrf as a parser to create pandas DataFrames and then perform aggregate analysis or create our own plots from there. Perhaps NetworkSet should be used on that aggregate calculations, especially for the sigma limits or comparisons to limit lines. Some data vs. plotting separation there.
> 
> So we don't generally use the built-in plotting, unless we are investigating networks. It is very handing in that case for me!
> 
> # Sponsored
> I appreciate your work. 🎉🚀 Thank you for what you do! 🙂

I have to say I do something similar, a measurement in which the circuit is modified step by step  - such as the temperature you mentioned. But since the datasets become very large easily I decided to move away from ASCII-based formats for storing the data. In my case I store a dataset in a hdf5 file, for instance the last one contained 201 networks. And instead of having 201 .s2p files i have single .h5 file.
So far I don't know how I would implement a hdf5 based scikit-rf interface. But it would at least worth a thought I guess. Maybe that's something one has to discuss deeply.

**Comment by jhillairet** [comment]
updated answers (35 answers on 10/09/2020)

**Comment by jhillairet** [comment]
Updated answers (41 answers 24/01/2021). Survey is now closed.

What should be ask for the next survey ?
