### ISSUE TITLE
dB mag calculation of S parameters is incorrect

### ISSUE THREAD

**Issue by josh1111** [scikit-rf/scikit-rf#36]
The current code uses mf.complex_2_db which simply does 20*log10(sqrt(real^2 + imaginary^2)). However this should be -20*log10(refl. coeff.) where refl. coeff = sqrt( (Real-Zo)^2 + Imag^2 ) / sqrt( (Real+Zo)^2 + Imag^2). 

The current code makes S11 match to the 50Z impedance circle on the smith chart vs. the 50 ohm point on the smith chart (assuming a 50 ohm source impedance). This means that your current S11 parameters dB mag give very wrong numbers.

**Comment by arsenovic** [comment]
@josh1111  is there a problem or can i close this?

**Comment by josh1111** [comment]
Hi Alex - Sorry for the late reply. I didn't see a notification on the first message you sent. I think the issue is that I assumed your S11 -> dB conversion was the dB mag of the return loss of S11. Not just the magnitude of the complex number S11.

**Comment by arsenovic** [comment]
ok, glad it makes sense now,

keep on truckin
