### ISSUE TITLE
Number of ports gets calculated wrong

### ISSUE THREAD

**Issue by cloidnerux** [scikit-rf/scikit-rf#366]
The calculation for the number of ports is wrong.
The nrows is `nports^2 * 2+1`, but the calculation only accounts for the square. It works for a two-port due to rounding, but nut for three or four ports. 
https://github.com/scikit-rf/scikit-rf/blob/577b957427d59ab3f4ae892ec7f1da89cb47757c/skrf/vi/vna/keysight_pna.py#L270
The correct code is
`nports = int(np.sqrt((nrows - 1)/2))`

**Comment by jhillairet** [comment]
Should be fix with PR #372
