### ISSUE TITLE
Check for equality rather than identity (SyntaxWarning on Python 3.8)

### ISSUE THREAD

**Issue by JAnderson419** [scikit-rf/scikit-rf#368]
Running skrf on python 3.8 will result in many warnings similar to the following:

```
SyntaxWarning: "is" with a literal. Did you mean "=="?
 if smithR is 1:
```

From the python 3.8 release notes:

> The compiler now produces a SyntaxWarning when identity checks (is and is not) are used with certain types of literals (e.g. strings, numbers). These can often work by accident in CPython, but are not guaranteed by the language spec. The warning advises users to use equality tests (== and !=) instead. (Contributed by Serhiy Storchaka in bpo-34850.)

To be in compliance with the language spec and prevent edge cases from causing problems, we should probably move all the is/is not statements over to == and !=

**Comment by jhillairet** [comment]
I've changed the `is` to `==` which generated Warnings `plotting.py` (in #375). There are probably some other in the code, but the tests did not made them appeared.
