### ISSUE TITLE
Module media import is broken for skrf >= 0.15

### ISSUE THREAD

**Issue by pfreidl** [scikit-rf/scikit-rf#387]
Servus *,

while upgrading from skrf 0.14.9 to the newest version on conda-forge i stumbled upon following problem:
when accessing skrf.media, i can no longer use the classes outside media.py (i.e. MLine, ...)

i tried to reproduce the problem in python 3.6, 3.7, and 3.8 via the anaconda 4.8.4 distribution on Windows10 using following commands:
```python
import skrf as rf
rf.media.MLine
```
which returns
`AttributeError: module 'skrf.media.media' has no attribute 'MLine'`
when accessing the the module itself via
```python
import skrf as rf
rf.media
```
skrf >= 0.15 returns
`<module 'skrf.media.media' from 'XXX\\envs\\py38\\lib\\site-packages\\skrf\\media\\media.py'>`

skrf=0.14.9 returns
`<module 'skrf.media' from 'XXX\\envs\\rf_notebook\\lib\\site-packages\\skrf\\media\\__init__.py'>`

can anyone reproduce this problem?

**Comment by jhillairet** [comment]
You are right, since 3-4 years now, most medias must be imported explicitly, like:

`from skrf.media import MLine`
