### ISSUE TITLE
Extract PNG generated by plot_s_() 

### ISSUE THREAD

**Issue by mwhy** [scikit-rf/scikit-rf#392]
Hello,

I'm having trouble finding out how to extract the pngs generated by the plot_s_smith() method for example.
I would like to display the image on a webpage so plt.show() does not do the trick.
I would be very grateful if somebody could tell me how to achieve this.

Cheers

**Comment by jhillairet** [comment]
If your matplotlib setup does not let you access to the save button :
![image](https://user-images.githubusercontent.com/4642848/94157798-e8e85d00-fe81-11ea-8cb7-9640cbcd36b3.png) 

you can create a matplotlib axe and use it to plot your figure inside (using the `ax=` parameter), then use it for saving the figure.

```
fig, ax = plt.subplots()
my_network.plot_s_smith(ax=ax)
ax.savefig('myfigure.png')
```

**Comment by beuerle** [comment]
You need to save the figure before you view.

```python
[...]
ptl.savefig('figurename.png')
plt.show()
[...]
```

reference: [`matplotlib.pyplot.savefig`](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.savefig.html)

**Comment by mwhy** [comment]
Thanks a lot to both of you!

If somebody else encounters this problem here is a way without having to save the image every time:
