### ISSUE TITLE
Touchstone parser issues with Ansys touchstone 2.0 files

### ISSUE THREAD

**Issue by lrayzman** [scikit-rf/scikit-rf#400]
Hello,

There are some issues parsing Touchstone 2.0 files generated by HFSS/Network Explorer.  
An example of such file is:
[ansys_test.zip](https://github.com/scikit-rf/scikit-rf/files/5362864/ansys_test.zip)

I've noticed three problems.  One is that the parser doesn't support `[matrix format]` keyword that is used by Ansys (although it only seems to generate full matrices). 

The parser is sensitive to location of  `[number of ports]` keyword when there are HFSS port names in the comments.  The comments precede the keyword. The parser seems to check the port number before the `rank` variable is assigned. And  `rank` is not know up front because this is a .ts file.

This is a mixed port reference case where  `[reference]` spans multiple lines -- and has in-line comment -- but the parser doesn't handle this situation.

LR

**Comment by jhillairet** [comment]
Indeed, for the moment, there is no proper support of Touchstone 2.0 files format (yet?)
