### ISSUE TITLE
skrf.Network() does not open an snp file from a pathlib.Path object

### ISSUE THREAD

**Issue by horror-vacui** [scikit-rf/scikit-rf#414]
I was told, that it is a good practice to handle filenames and paths as pathlib.Path objects, because they can save me from a few issues. Unfortunately skrf's Network function can not create from such a path a Network object.

I am not sure it is a bug, because there is a pretty simple workaround, see last command in my code. I just thought it's worth to give a feedback to you.

```
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pathlib import Path
>>> import skrf as rf
>>> rf.__version__
'0.15.4'
>>> p = Path("autag_cabling_atten0dB.s2p")
>>> rf.Network(p)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tibenszky/.local/lib/python3.6/site-packages/skrf/network.py", line 415, in __init__
    self.read(fid)
  File "/home/tibenszky/.local/lib/python3.6/site-packages/skrf/network.py", line 2132, in read
    self.copy_from(read(*args, **kwargs))
  File "/home/tibenszky/.local/lib/python3.6/site-packages/skrf/io/general.py", line 118, in read
    obj = pickle.load(fid, *args, **kwargs)
TypeError: file must have 'read' and 'readline' attributes
>>> rf.Network(str(p.resolve()))
2-Port Network: 'autag_cabling_atten0dB',  55000000000.0-65000000000.0 Hz, 101 pts, z0=[50.+0.j 50.+0.j]
```

**Comment by JAnderson419** [comment]
Thanks for bringing this up! I'll add a check for Path-type objects into Network so that you don't have to use a workaround like this. Pathlib was introduced in 3.4, so Python 2 users still won't be able to use pathlib, but the vast majority of users are on Python 3 at this point anyways.

Jackson
