### ISSUE TITLE
Touchstone.get_comment_variables() crops decimals

### ISSUE THREAD

**Issue by Grobson97** [scikit-rf/scikit-rf#426]
## My code
```
touchstoneFile = rf.io.touchstone.Touchstone(directory + filename)

## Print simulation parameter values
variables = touchstoneFile.get_comment_variables()
print(variables)
```

## Output
`{'Lk': ('0', ''), 'nb_lk': ('0', ''), 'len': ('100', ''), 'ustrip_lw': ('2', ''), 'capin': ('12', ''), 'capout': ('20', ''), 'resw': ('73', ''), 'capin2': ('20', ''), 'P3_width': ('2', '')}` 

## Expected output
`{'Lk': ('0.03', ''), 'nb_lk': ('0.03', ''), 'len': ('100.0', ''), 'ustrip_lw': ('2.5', ''), 'capin': ('12.0', ''), 'capout': ('20.0', ''), 'resw': ('73.0', ''), 'capin2': ('20.0000041', ''), 'P3_width': ('2.5', '')}`

## Header of `.s3p` file:
```
! Sonnet Data File
! From: sonnet Version : 17.52.2
! From Emgraph Data: 
! Data File Written: 02/19/2021 11:48:18
!< HDATE 02/16/2021 15:44:18
!< MDATE 02/16/2021 15:44:18
!< PARAMS
!< Lk = 0.03
!< nb_lk = 0.03
!< len = 100.0
!< ustrip_lw = 2.5
!< capin = 12.0
!< capout = 20.0
!< resw = 73.0
!< capin2 = 20.0000041
!< P3_width = 2.5
!< END PARAMS
# GHZ S RI R 19.54500
```

**Comment by jhillairet** [comment]
fixed by @JAnderson419 on #427
