### ISSUE TITLE
port names in subnetwork()

### ISSUE THREAD

**Issue by luar123** [scikit-rf/scikit-rf#429]
I like the new subnetwork method, however, it misses the functionality of working on port names instead of port indices Additionally, existing port names get lost when creating a subnetwork.

For now, I use this workaround:
```python
nwk1 =rf.Network(...)
extract_ports = [Port_A, Port_C, Port_Z]  # list of port names to extract
extract_ports_idx = [nwk1.port_names.index(p) for p in extract_ports]  # get port indices
sub_nwk1 = nwk1.subnetwork(extract_ports_idx)
sub_nwk1.port_names = extract_ports  # copy port names
```
It would be great if this functionality could be implemented in the subnetwork method directly.

**Comment by jhillairet** [comment]
Sorry for the delay @luar123 , this issue has been forgotten. Will be integrated in next release.
