### ISSUE TITLE
Select S-parameter at a certain frequency

### ISSUE THREAD

**Issue by blurLake** [scikit-rf/scikit-rf#430]
Hi, I am quite new to scikit-rf package. I have a question about how to fetch s parameters using frequency. 

Say I have a network with S parameters  rf.s corresponding to frequencies [4000, 4002, 4004, 4006] (which could be much longer). How can I select the S matrix for a certain frequency? And more importantly, is there a built-in method to get S matrix at frequency 4003 which is not in the list?

Thanks for the help!

**Comment by arsenovic** [comment]
great to hear, 

https://scikit-rf.readthedocs.io/en/latest/tutorials/Networks.html#Slicing

https://scikit-rf.readthedocs.io/en/latest/api/network.html#interpolation-and-concatenation-along-frequency-axis

these should help,  you should join the mailing list for more questions like this,   

alex
