### ISSUE TITLE
Example notebooks are broken: ModuleNotFoundError

### ISSUE THREAD

**Issue by Vinc0110** [scikit-rf/scikit-rf#462]
The example notebooks on RTD are broken: `ModuleNotFoundError: No module named 'skrf'`.
I'm not yet sure what's going on.

**Comment by jhillairet** [comment]
seems linked to the suppression of the line : 
`git+https://github.com/scikit-rf/scikit-rf.git@master`
in `requirements.txt`. 

But there is the following line in `doc/source/conf.py`:
`sys.path.insert(0, os.path.abspath('../../'))`
which should allow importing the package correctly... I'm puzzled.

**Comment by FranzForstmayr** [comment]
> But there is the following line in `doc/source/conf.py`:
> `sys.path.insert(0, os.path.abspath('../../'))`
> which should allow importing the package correctly... I'm puzzled.

This is only valid for the conf.py file I assume, the runipy will run in a seperate session.

**Comment by jhillairet** [comment]
OK, fixed with #464
