### ISSUE TITLE
Problem with the circuit builder - “LinAlgError: Singular matrix” error

### ISSUE THREAD

**Issue by andresmmera** [scikit-rf/scikit-rf#466]
Hello all,

As reported in the scikit-rf google group, the bandpass filter example [1] is not working. I copied and pasted it in my jupyter notebook just changing the freq definition line, but it breaks where the connections matrix is passed and it gives the following error: “LinAlgError: Singular matrix”.

Please find the source and the complete error log in the links [2] and [3].

[1] https://scikit-rf.readthedocs.io/en/latest/examples/circuit/Lumped%20Element%20Circuits.html#Pass-band-filter

[2] Complete error log: https://gist.github.com/andresmmera/c459801297078a5bc7120a5f55b65131

[3] Source: https://gist.github.com/andresmmera/42e6c29625f55251fa90689c22d8ccc5

**Comment by jhillairet** [comment]
Thank you for reporting. 

This bug is interesting:
- the code passes under my Windows 10 Python 3.7.8 and 3.8.10
- it passes under my Linux Python 3.7.7 but fails with Python 3.8.8
- The example is tested in the Continuous Integration which is supposed to be Linux environment : it passes Python 3.6, 3.7 and 3.8, 

@andresmmera what is your configuration?

**Comment by andresmmera** [comment]
Thank @jhillairet for your support.

I'm using Python 3.8.0 (through a jupyter notebook) with Linux. My system settings are the following:

  Operating System: Ubuntu 18.04.5 LTS
  Kernel: Linux 4.15.0-20-generic
  Architecture: x86-64

![image](https://user-images.githubusercontent.com/13180689/118093147-545d4b80-b3cd-11eb-9401-30f2f5dff27c.png)

![image](https://user-images.githubusercontent.com/13180689/118093322-925a6f80-b3cd-11eb-8163-b432fc50355d.png)

**Comment by jhillairet** [comment]
Thank you. The error comes from the frequency point in your code which is exactly 0, which creates NaN in the scattering parameters (for the inductance) and Numpy can honestly complain about that.  

Could you retry changing:

`freq = rf.Frequency(start=0, stop=1, npoints=501, unit='GHz')`

into, for example:

`freq = rf.Frequency(start=0.1, stop=1, npoints=501, unit='GHz')`

**Comment by andresmmera** [comment]
Indeed, having f_start > 0 solved the problem.

Thank you very much for your help!
