### ISSUE TITLE
HFSS Touchstone File - Incorrect Port Impedance Array

### ISSUE THREAD

**Issue by lstuemke** [scikit-rf/scikit-rf#470]
I'm having a problem with sNp files exported from HFSS having the wrong port impedance. Specifically, every port after port1 is labeled as 0ohm.

In skrf.io.touchstone, there is a function called get_gamma_z0() that expects the port impedance matrix to be a single line:

![image](https://user-images.githubusercontent.com/49922901/118688786-5dd32300-b7d4-11eb-94db-dcc8e3f4f522.png)

However, the port impedance matrix is not always listed as a single line. For example:

![image](https://user-images.githubusercontent.com/49922901/118689044-9ffc6480-b7d4-11eb-855a-0d7715345019.png)

Clearly, each of the 4-ports is 50ohm. But since get_gamma_z0() only looks at the line starts with '! port_impedance', it misses the other 3 matrix rows, labeling them as 0ohm.

It looks like there's code that might address this in the 'else' clause, but this code never executes because nb_elem is in fact equal to 2*self.rank:

![image](https://user-images.githubusercontent.com/49922901/118690029-a50de380-b7d5-11eb-8874-df14e6999f14.png)

**Comment by jhillairet** [comment]
Thanks for reporting. Is it a Touchstone file from an HFSS Driven terminal solution or from HFSS 2020 R1?

**Comment by lstuemke** [comment]
It's Driven Modal, HFSS 2020R1.

**Comment by jhillairet** [comment]
Yes. That very particular version of HFSS exports gamma and Z0 in matrix form (why?), then went back to the previous convention in the following version. (Note matrix form is also the case when generated from a Driven terminal solution.) Can you upgrade your version? kind of duplicate of #354

**Comment by jhillairet** [comment]
I mean, it's not a bug from scikit-rf, it's a change of the way HFSS formats its Touchstone file (gamma and z0 at not part of the Touchstone format, so it's a feature from HFSS they implement into the comments). Since they have changed back this formatting in 2020R2 and later, the question for us is should we support this particular version of HFSS?

**Comment by lstuemke** [comment]
Ahh okay, yeah if they changed back in the next release then this should go away when I update my Ansys. No need to support 2020R1 on my account.

**Comment by jhillairet** [comment]
a workaround for HFSS 2020R1 is to manually set the characteristic impedance :
`ntw.z0 = 50`
and eventually the same for gamma if you need it...
