### ISSUE TITLE
Join Slack workspace

### ISSUE THREAD

**Issue by Vinc0110** [scikit-rf/scikit-rf#487]
How to join the scikit-rf workspace on Slack? I'm not familiar with Slack, but it seems I need an invitation.

**Comment by jhillairet** [comment]
The following link doesn't work ? 

https://scikit-rf.slack.com/

**Comment by Vinc0110** [comment]
The link works, but I only get to a login dialog, which fails with:
`It looks like there isn’t an account on scikit-rf tied to this email address.`

**Comment by JAnderson419** [comment]
Try this:

https://join.slack.com/t/scikit-rf/shared_invite/zt-d82b62wg-0bdSJjZVhHBKf6687V80Jg

**Comment by Vinc0110** [comment]
That worked. Thanks!
