### ISSUE TITLE
Pyc files under version control

### ISSUE THREAD

**Issue by TheWylieStCoyote** [scikit-rf/scikit-rf#49]
I am not sure why there are .pyc under version control in the [skrf/pythonicsInstruments](https://github.com/scikit-rf/scikit-rf/tree/master/skrf/pythicsInstruments) folder. Moreover the source files are not  present.

**Comment by arsenovic** [comment]
yes i probably meant to remove these. i ll do this. 

if you are interested in pythics, you probably can find the files in the git history. 

i have moved to using either 
*  the ipython notebook's  widgets for simple ui's
* traitsui for more complex UI's

**Comment by arsenovic** [comment]
[here](http://nbviewer.ipython.org/github/scikit-rf/examples/blob/master/VNA%20Control.ipynb) is an example of simple VNA data retrieval with ipython's interact function. 

also note that it uses the new python-ivi backend, which is a very recent addition

**Comment by arsenovic** [comment]
i removed that folder, as it was really old and not supported
