### ISSUE TITLE
Moving wiki docs into main documentation ?

### ISSUE THREAD

**Issue by jhillairet** [scikit-rf/scikit-rf#496]
Currently, the [main documentation](https://scikit-rf.readthedocs.io/en/latest/index.html) does not include some of the documentation which is on the [Github wiki](https://github.com/scikit-rf/scikit-rf/wiki), such like [the development guide](https://github.com/scikit-rf/scikit-rf/wiki/Development) of the [citation/acknowledgment discussion](https://github.com/scikit-rf/scikit-rf/wiki/Citations-Acknowledgments).

Two questions:

1) should we include the wiki documentation in the main documentation?
2) should we keep the wiki documentation?

for 1) I think so, but for 2) I don't know. Google doesn't reference the documentation in the wiki, and keeping the same documentation in two places is probably a bad idea. 

What do you think?

**Comment by arsenovic** [comment]
i think we should consolidate docs, and get rid of the wiki.

**Comment by jhillairet** [comment]
close after #500
