### ISSUE TITLE
Type hints in API docs

### ISSUE THREAD

**Issue by Vinc0110** [scikit-rf/scikit-rf#506]
Now that scikit-rf starts to have type hints included in many classes, I'd like to propose a change in the `autodoc` configuration for the generation of the API documentation with Sphinx.

In summary, I think we should set `autodoc_typehints = "description"`.

Details:

Currently, the displayed signatures of class functions include the type hints, which provides redundant information and degrades readability when many parameters are listed. For example, here is a screenshot of the current `VectorFitting.vector_fit()` [documentation](https://scikit-rf.readthedocs.io/en/latest/api/vectorFitting.html#skrf.vectorFitting.VectorFitting.vector_fit) with a rather messy signature at the top:

![image](https://user-images.githubusercontent.com/63644854/127916398-4f45e8c2-d2d7-4eff-9e9c-63ab0758b3c2.png)

This behavior can be changed in the Sphinx configuration, for example by setting `autodoc_typehints = "description"`. See www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_typehints

For comparison, here is a screenshot of a [NumPy function doc](https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html), which I think looks much nicer:

![image](https://user-images.githubusercontent.com/63644854/127916763-827bcbfc-5518-48d5-a4c1-8d0a7f01ad6d.png)

**Comment by FranzForstmayr** [comment]
In addition to that, the type in the docstring is redundant, it's enough to annotate the parameter in the signature.
I already thought of that when adding the first type hints in `network.py`, but the documentation style seemed to be incomplient with the `autodoc-typehints` scheme. However it seems that this should be possible [https://github.com/agronholm/sphinx-autodoc-typehints#compatibility-with-sphinxextnapoleon](typehints with napoleon)

**Comment by Vinc0110** [comment]
You are right, but I'm not sure if it's worth the extra effort of installing and configuring the extension and updating all the docstrings (do they have to be updated?). After all, the function signatures have already been updated and the rendered results on RTD would be exactly the same as they currently are.

**Comment by jhillairet** [comment]
Looking to the issues in autodoc-typehints, [in particular this one](https://github.com/agronholm/sphinx-autodoc-typehints/issues/167), it seems it is redundant to install autodoc-typehints and to define:
`autodoc_typehints = "description"` 
in the sphinx config. 

I did both locally (with autodoc-typehints and without the "description" parameter and vice&versa) and I didn't find a difference in the rendering.

**Comment by lenadevids** [comment]
is there any algorithm or program which detect when [Microwave Recycling](https://greencitizen.com/microwave-recycling-how-to-dispose-of-your-microwave-oven/) is process should be done.

**Comment by FranzForstmayr** [comment]
@lenadevids 
I'm afraid to say this project is about radio frequency engineering and not about microwave ovens.

**Comment by digitalblocs** [comment]
We are a [Houston seo service](https://digitalblocs.com/seo-for-small-businesses/) website design enhancement administration based Digital Blocs Company that works with organizations, all things considered, from one side of the country to the other and in an assortment of businesses to assess the opposition..

**Comment by suorinvape** [comment]
You are right, but I'm not sure if it's worth the extra effort of installing and [configuring](https://suorinvape.com/collections/salt-e-liquid) the extension and updating all the docstrings (do they have to be updated?).

**Comment by Vinc0110** [comment]
I'm closing this issue to stop the spam. We are probably done here anyways.

**Comment by giftforhim** [comment]
[https://www.hentley.co/](url) must visit to having good and 100 percent quality handmade leather wallets .

**Comment by suorinairpluspod** [comment]
is there any algorithm or program which detect when <a href="https://suorinvape.com/collections/suorin-air-plus">Suorin Air Plus Pod</a> is process should be done. if not visit our site
