### ISSUE TITLE
Package installs pathlib

### ISSUE THREAD

**Issue by DavidLutton** [scikit-rf/scikit-rf#512]
[reqirements.txt](https://github.com/scikit-rf/scikit-rf/blob/master/requirements.txt) includes [pathlib](https://pypi.org/project/pathlib/) which states ```"Attention: this backport module isn’t maintained anymore"``` 

If you need to support Python < 3.4 use the [PEP 0508](https://www.python.org/dev/peps/pep-0508/#examples) syntax for python_version so pathlib is not installed when the Python version is > 3.4.

Also seen in [requirements/base.pip](https://github.com/scikit-rf/scikit-rf/blob/master/requirements/base.pip)

**Comment by jhillairet** [comment]
As Python 2 and <3.4 is no more supported, pathlib is probably no more needed. tbc.
