### ISSUE TITLE
Readthedocs Stable Build

### ISSUE THREAD

**Issue by Vinc0110** [scikit-rf/scikit-rf#513]
For some reason, the docs on [readthedocs ](https://scikit-rf.readthedocs.io) get built in two versions: *latest* and *stable*. As I noticed, the two versions are currently out of sync. *Latest* is up to date (built on Aug. 5th), but *stable* is outdated (built on June 28th). Also see the [build logs](https://readthedocs.org/projects/scikit-rf/builds).

This is problem, because Google searches for skrf functions are sometimes (always?) pointing to the *stable* docs.

Unless there is a good reason for these two versions, I propose to delete *stable*.

**Comment by jhillairet** [comment]
> the two versions are currently out of sync. _Latest_ is up to date (built on Aug. 5th), but _stable_ is outdated (built on June 28th)

Indeed. I desactivated the "stable" branch.
