### ISSUE TITLE
Angular frequency has contradicting type hints

### ISSUE THREAD

**Issue by Aikhjarto** [scikit-rf/scikit-rf#527]
skrf.frequency.Frequency.w has contradicting type hints

In the function definition, it says correctly `npy.ndarray`
https://github.com/scikit-rf/scikit-rf/blob/cdd0ee29c5b8f53b25552aeffe2982fdfb866362/skrf/frequency.py#L525

but in the docstring it incorrectly says `w : :class:`numpy.ndarray``
https://github.com/scikit-rf/scikit-rf/blob/cdd0ee29c5b8f53b25552aeffe2982fdfb866362/skrf/frequency.py#L533

**Comment by jhillairet** [comment]
Closed with #542
