### ISSUE TITLE
write_touchstone appends port impedance to each frequency line

### ISSUE THREAD

**Issue by gabrovche** [scikit-rf/scikit-rf#534]
Hi,

not sure if that's a bug or a feature, but the function write_touchstone in version '0.19.0' 
would append Port Impedance comment/line after **each** frequency line - like this:

```
!My_Dataset_Name
!Created with skrf (http://scikit-rf.org).
# Hz S RI R 50.0 
!freq ReS11 ImS11
300000.0 0.9921585989441424 -0.0072647626521898144
! Port Impedance 50.00000000000000 0.00000000000000 
400000.0 0.9911993160206137 -0.008323621860210042
! Port Impedance 50.00000000000000 0.00000000000000 
500000.0 0.9914028637910609 -0.009839535717644414
! Port Impedance 50.00000000000000 0.00000000000000 
600000.0 0.9908047368439974 -0.011445824163910672
! Port Impedance 50.00000000000000 0.00000000000000 
700000.0 0.9905877864557537 -0.012951901021320895
! Port Impedance 50.00000000000000 0.00000000000000 
```
... and so on!

Can anyone explain why is this the preferred method (i.e. can the port impedance change with each frequency?) or have it fixed (e.g. by shifting that line insertion snippet above the for loop) if not the original intention?

Thank you in advance!

**Comment by jhillairet** [comment]
Actually, this is a feature. This behaviour reproduces the one from ANSYS HFSS, as indeed in some cases the characteristic impedances can depend on the frequency (ex: waveguides). This should only appear when using the parameter  `write_z0=True` in `write_touchstone`
