### ISSUE TITLE
NetworkSet with arbitrary number of independant variables

### ISSUE THREAD

**Issue by vik-s** [scikit-rf/scikit-rf#535]
Is there a way to use `NetworkSet` to hold network objects with an arbitrary number of independent variables, for example, bias conditions, geometry, temperature, etc? It would be convenient because one could analyze network properties such as gain, or other derived metrics versus these independent variables?

My particular use case for something like this would be to plot the fT/fMax of a transistor versus bias voltage/current, which is a commonly generated plot for rf-transistors.

Furthermore, it would be great to support import from MDIF format (ADS) or MDL format (ICCAP) both of which contain bias dependent s-parameters usually, but this could be implemented down the road.

Any thoughts on if this can already be done? Or how one should go about implementing this?

**Comment by arsenovic** [comment]
https://github.com/hftools/hftools

**Comment by jhillairet** [comment]
PR #585 should add the desired feature, except for MDL files (yet?)
