### ISSUE TITLE
Can't get Qtapps module to work

### ISSUE THREAD

**Issue by ruizhi92** [scikit-rf/scikit-rf#544]
The Qtapps module seems to be a compact and nice module. But when I tried to install the environment of Qtapp module by 
`conda env create --file skrf_qtapps_py35.yml`, some error pop up. The last line in the file "prefix:/home/alex/anaconda3/envs/vincepy35" seems to be user-specific and should be removed? After I made the changes, there still exists conflicts among the required packages. I tried to relax some version specifications but can't get it to work.

Can you help with this issue? Thanks.

**Comment by FranzForstmayr** [comment]
Should be fixed in #790, at least with pyqt5.
