### ISSUE TITLE
How to use differential ports by scikit-rf

### ISSUE THREAD

**Issue by jinzhaohu** [scikit-rf/scikit-rf#546]
Hi:

When I use CST software, there is a function called "use differential ports", see http://www.mweda.com/cst/cst2013/mergedprojects/CST_DESIGN_STUDIO/components/block/usingdifferentialports.htm

It allows me to make 2-ports network to 4-ports network. Can I realize the same function by scikit-rf? How can I do that?

Thanks!

**Comment by jhillairet** [comment]
Dear @jinzhaohu, 
Is the following answer your issue?
https://scikit-rf.readthedocs.io/en/latest/examples/mixedmodeanalysis/Mixed%20Mode%20Basics.html

**Comment by jinzhaohu** [comment]
Dear Julien:

Very thx for your kind reply. However, it cannot solve this problem. Besides the function you mentioned, we tried the on_port_2_two_port function. It seems this one is closer. I can transfer an s1p to an s2p. But still, the s2p file is different from the one I generated from ADS. 

In ads, I use a single reference pin to change the s1p touchstone's default reference ----ground to a 50ohm port, then I generated an s2p from it. I am still finding a solution. If I find a way to solve it, we will try to write a new function and then submit a pull request. 

Thanks! If you have any new ideas, please also let us know.

**Comment by jinzhaohu** [comment]
I think the problem is on the impedance matching. However, when I check the source code of the one_port_2_two_port function, it seems Z0 never be used for calculation. Maybe this is the key point?

https://scikit-rf.readthedocs.io/en/latest/_modules/skrf/network.html?highlight=one_port_2_two_port

**Comment by jhillairet** [comment]
@JAnderson419 has much more experience than I have on mixed mode. What do you think?

**Comment by jinzhaohu** [comment]
Dear Julien:

We just solved this problem. Now we can transfer 1 port network to 2 ports network like HFSS or ADS. You can close this issue and we will try to submit a pull request later. You can merge it after reviewing it if you think it is useful.

Thanks so much.

**Comment by jhillairet** [comment]
could you explain in few words how you've made it ?

**Comment by jinzhaohu** [comment]
> could you explain in few words how you've made it ?

Sure. For an s1p file, I transfer it to y parameter. Then transfer the y parameter to a 2*2 matrix, where y11 is the original y parameter, y22=y11, y21=y12=-y11. Then transfer the new y matrix to S parameters with y2s function. Now, a 2 port network is created. 

Pretty like the function one_port_2_two_port. However, the one_port_2_two_port function can only realize lossless network transfer, while the new way keeps the information of the resistance in the s1p network. Although, to be honest, I don't know why...

It should be able to expand to any snp file, just realize the same function like this in a lot of commercial software like HFSS or ADS or CST:

http://www.mweda.com/cst/cst2013/mergedprojects/CST_DESIGN_STUDIO/components/block/usingdifferentialports.htm

**Comment by JAnderson419** [comment]
Hello,

Thanks for the explanation of what you carried out. It sounds like conceptually you have a single differential port that you are trying to transform back to a single ended port representation with two terminals? You might be able to do this transformation easier with current functionality by creating a two port network with only a differential component in the mixed mode matrix (no cc, cd, or dc terms) and using gmm2se to transform it back to single ended (there might be a 180 degree phase shift in the gmm2se function - I have not tracked down the cause yet in the linear algebra). If this does work for you, let us know. This is not something I typically do, but would make a good use case for a tutorial for others like you who are doing differential simulations.
