### ISSUE TITLE
Assert 'port' in portname?

### ISSUE THREAD

**Issue by TL-SjoerdOptLand** [scikit-rf/scikit-rf#547]
https://github.com/scikit-rf/scikit-rf/blob/b89f9f85f8595761fc5182dd6ddc4dea94b2fd5d/skrf/circuit.py#L222

I spent quite a while to figure out that 'input' was not a valid port name. Would it be an idea to assert that the portname actually contains 'port'?

**Comment by jhillairet** [comment]
Yes, you are right, it is a good idea.

Le ven. 29 oct. 2021 13:41, TL-SjoerdOptLand ***@***.***> a
écrit :
