### ISSUE TITLE
Vector Fitting: Error in equation?

### ISSUE THREAD

**Issue by dxxx9** [scikit-rf/scikit-rf#570]
Is it possible that there is an description mistake in the [first Vector Fitting equation](https://scikit-rf.readthedocs.io/en/latest/tutorials/VectorFitting.html) of the docs? The one to calculate the transfer function of a system.

My suggestion is that instead of the zeros (z_k) in the numerator it should be the residues (c_k) because it's a sum of partial fractions and therefore has no zeros in this form. Sure you can calculate the zeros from that partial form but I'm wondering if that should be the residues instead of the zeros there.

So, instead of this:
<img width="213" alt="aa" src="https://user-images.githubusercontent.com/62398752/142014856-3d9fc98c-2656-4153-8ad6-ef672c5e32dc.png">
is should be this?
<img width="213" alt="bb" src="https://user-images.githubusercontent.com/62398752/142014880-588b24c2-c4d1-4d7b-a78e-84f41a06aec7.png">

Please let me know if I'm wrong here.
Thanks!

[Github Permalink to docs](https://github.com/scikit-rf/scikit-rf/blob/c50c7cc9444d03145be22d40e3c72d863b0abdf8/doc/source/tutorials/VectorFitting.ipynb?short_path=5e8554d#L19)

**Comment by Vinc0110** [comment]
You are right, thanks for the hint! I was lazy with the naming/notation (also in the source code).

Of course, the tutorial should not contain errors and needs to be corrected, but I highly recommend you use the actual vector fitting paper instead if you want to study the algorithm in more detail. It confirms your suspicion:

![vf_eq2](https://user-images.githubusercontent.com/63644854/142023824-d62b9ccf-7f0e-42f3-95c1-f8750fa74b97.png)

**Comment by dxxx9** [comment]
Thanks for the response! Yes, I use the the original paper. That's how I noticed the difference. Just wanted to let you guys know. 👍

**Comment by Vinc0110** [comment]
That's good. Thanks again. I'll correct the tutorial and the variable names in the source code soon.

By the way: Depending on how deep you dig into vector fitting, you might find other mistakes or weird things in the examples or the code. Feel free to report any problems or make suggestions/requests for extra features. The module is still relatively new and, so far, I only implemented a limited set of features, which I find useful or interesting. Lot's of things could be extended or improved...

**Comment by dxxx9** [comment]
@Vinc0110 Thanks for correcting. If I stumble over something, I will let you know.
