### ISSUE TITLE
scikit-rf 2021 survey results

### ISSUE THREAD

**Issue by jhillairet** [scikit-rf/scikit-rf#573]
Dear scikit-rf users,

We have made a short survey intended for all the users of the scikit-rf, to:
- better know the users and the usages,
- determine what are the functionalities used the most and the less,
- find the ones which could be improved,
- define new directions for developments.

Could you please fill this short (5 min or less) and anonymous survey by following the link below:

https://forms.gle/uonurVVb4FPhTLQm9

Thanks in advance for your time,

The results will be posted in this issue.

**Comment by jhillairet** [comment]
![image](https://user-images.githubusercontent.com/4642848/143686123-38855799-1d64-4683-8d4c-c6e082c631f2.png)

![image](https://user-images.githubusercontent.com/4642848/143686128-967d53ec-179a-44b7-9484-6eeeb6e59ed4.png)

![image](https://user-images.githubusercontent.com/4642848/143686129-9b1d853a-c2a9-42d1-a1eb-36614d4a8788.png)

![image](https://user-images.githubusercontent.com/4642848/143686132-69d638c7-be45-484b-a267-474f3b0fb66a.png)

![image](https://user-images.githubusercontent.com/4642848/143686139-da85923a-b23c-4f0c-8931-248e6bb85d33.png)

![image](https://user-images.githubusercontent.com/4642848/143686146-5597b8d8-2e61-4acf-bfea-9a16f172358e.png)

![image](https://user-images.githubusercontent.com/4642848/143686148-4dea33d1-8548-45bd-b537-c9ed64ae3de5.png)

![image](https://user-images.githubusercontent.com/4642848/143686155-6a773ee6-439a-4b1f-859a-26f500d431a4.png)

![image](https://user-images.githubusercontent.com/4642848/143686159-90abc594-2d1b-41b9-9c72-ea15a039dc91.png)

![image](https://user-images.githubusercontent.com/4642848/143686162-04bd66a4-a68e-4cc0-bee7-315940dd96c1.png)

![image](https://user-images.githubusercontent.com/4642848/143686164-d8b4cab2-021c-48a1-ba69-92f41a6b83e4.png)

![image](https://user-images.githubusercontent.com/4642848/143686166-b7840fb5-ff9c-498f-85b4-12131139304f.png)

![image](https://user-images.githubusercontent.com/4642848/143686167-5444e894-3ee3-446d-a5fa-2adf48a8986b.png)

On improvements/doc :
Could you give some details on your previous answer?
•	Ways to work with, run functions on, and extra various summary parameters from multi-dimensional collections of Networks, with varied independent variable (like temperature, bias conditions, etc). I was not aware of NetworkSet from the above question so I'll have to check that one out too. 
•	More examples and case studies to not only explain the basics of the package but also to show some neat use of it...
•	More examples; sometimes the documentation is somewhat obscure,
•	It would be nice to have filter design features such as coupling matrix synthesis, etc.
•	Perhaps integration with ADS/CST or other well known EM simulation packages? 
•	hands-on tutorial notebooks/presentation that could be given to engineering colleagues to introduce them to skrf
•	Multidimensional touchstone arrays, like sweep over temperature or something else. 
•	Line-up calculation tools.
•	More flexibility in the option of circuit analysis using S-parameter blocks and typical passive circuit elements.
•	More documentation is always good :-)
•	Multi-language support for documentation
•	More examples, tutorials of features

**Comment by jhillairet** [comment]
updated answers (28 so far... quite a small number!)

**Comment by arsenovic** [comment]
julien you should have a link to your GH sponsors on scikit-rf page, since you are current maintainer.  looks like quite a few people consider sponsorship.
