### ISSUE TITLE
Touchstone parser does not accept alternative encodings

### ISSUE THREAD

**Issue by CratesDeThebes** [scikit-rf/scikit-rf#586]
Any encoding that is an alternative to default UTF-8 makes touchstone parsing fail.

This is because encoding should be an argument to skrf.Network and in /skrf/io/touchstone.py the line 74 that is
`fid = get_fid(file)`
should be replaced by 
`fid = get_fid(file,encoding)`

**Comment by jhillairet** [comment]
Welcome and Thanks for reporting this issue. Do you have an example of a failing Touchstone file you could attach?

**Comment by CratesDeThebes** [comment]
Thank you for your quick comment. Here is a MWE, it is a s2p file including a comment with a french accent and encoded with ISO-8859-15.
[test.s2p.zip](https://github.com/scikit-rf/scikit-rf/files/7718032/test.s2p.zip)

**Comment by jhillairet** [comment]
Raah, sacré français alors ;-)

I can't reproduce under Windows 10:
```python
>>> import skrf as rf
>>> rf.__version__
Out[17]: '0.20.0'

>>> ntwk = rf.Network('test.s2p')
>>> ntwk.s
Out[18]: 
array([[[ 1.-1.j,  1.-1.j],
        [-1.+1.j,  1.-1.j]]])

>>> ntwk.comments
Out[16]: ' Comment with a french accent : é\n'
```
Which version and what OS are you using?

**Comment by CratesDeThebes** [comment]
Tout à fait !
Here are the versions of scikit-rf and the OS I use:

```
> pip3 show scikit-rf
Name: scikit-rf
Version: 0.19.0
```

> uname -a
Linux XXXXXX 5.10.0-0.bpo.9-amd64 #1 SMP Debian 5.10.70-1~bpo10+1 (2021-10-10) x86_64 GNU/Linux

**Comment by jhillairet** [comment]
@CratesDeThebes were you aware of the particular encoding of the file or not before running into the bug? 

I mean, if the encoding is on purpose and known in advance, one could specify the encoding when creating the Network, by passing an `encoding` parameter. 

If not, we need to guess the particular encoding, which is not easy and mostly a trial-and-error thing. In #587 I ended up using latin1 as a fallback if utf8 fails, which should work in most situation, but is not perfect either.

**Comment by CratesDeThebes** [comment]
Thank you for the fix.

I was not aware of the encoding, I noticed the bug when I received files from users who run a different OS (MS-Windows whereas I use a GNU-Linux distro.

In my opinion, the best way would be to enable the possibility for the user to specify an encoding kwarg, defaulting this argument to UTF-8, try to guess the encoding if reading fails, falling back to latin-1 if it fails again and finally output an error if all that fails, which should be rare.

**Comment by jhillairet** [comment]
OK, I've added the possibility to define the encoding type in `Network`. If not defined, `Touchstone()` makes a trial-and-error.
