### ISSUE TITLE
Notch gating in tdr

### ISSUE THREAD

**Issue by tuxgvf** [scikit-rf/scikit-rf#608]
Hi guys,
You are doing an excellent job! Let me add some ideas here. Adding the possibility of doing a notch gating in tdr transform.
Thanks

**Comment by jhillairet** [comment]
Would you have some references, documentation or examples so start with?

**Comment by denzchoe** [comment]
@tuxgvf,

I believe notch should already exist.
See doc api 

https://scikit-rf.readthedocs.io/en/latest/api/generated/skrf.time.time_gate.html#skrf.time.time_gate


`mode = bandstop`
