### ISSUE TITLE
DeprecationWarning: convolve1d from namespace scipy.ndimage.filters is deprecated

### ISSUE THREAD

**Issue by TM90** [scikit-rf/scikit-rf#622]
I am getting DeprecationWarnings wenn using the Network Object

convolve1d should be importet from scipy.ndimage instead of scipy.ndimage.filters
Message from scipy:
For me in network.py in line 179 and time.py line 20:

`DeprecationWarning: Please use convolve1d from the scipy.ndimage namespace, the scipy.ndimage.filters namespace is deprecated`

**Comment by TM90** [comment]
This seems to be already fixed but not released ?

**Comment by jhillairet** [comment]
yes indeed, it has been fixed in #620 by @l-johnston. It will be included in the next version to come (probably next week?)

**Comment by jhillairet** [comment]
Anyway, thanks for reporting!

**Comment by TM90** [comment]
Thanks!
