### ISSUE TITLE
se2gmm: singular matrix when multiple single-ended ports

### ISSUE THREAD

**Issue by Ttl** [scikit-rf/scikit-rf#636]
The following code that tries to convert only one differential pair in 4-port to mixed mode S-parameters raises `numpy.linalg.LinAlgError: Singular matrix` error.

```
import numpy as np
import skrf

ports = 4
s_random = np.random.uniform(-1, 1, (1, ports, ports)) + 1j * np.random.uniform(-1, 1, (1, ports, ports))
net = skrf.Network(s=s_random, f=[1], z0=50)
net.se2gmm(p=1)
```

The same issue seems to happen when there are more than one single-ended port in the result.

`ports=5` and `p=2` raises a different error: 

``` 
File "skrf/network.py", line 3561, in _P
    Pa[l, 4 * p + 2 * (l + 1) - 1 - 1] = True
IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by jhillairet** [comment]
closed by #635
