### ISSUE TITLE
NameError: name 'Frequancy' is not defined

### ISSUE THREAD

**Issue by j0hu3ttl** [scikit-rf/scikit-rf#640]
Use of the newly implemented IEE370 deembedding methods #628 throws an error if using non-uniform frequency vectors.
It seems there are two typos in [deembedding.py](https://github.com/scikit-rf/scikit-rf/blob/master/skrf/calibration/deembedding.py)

Line 1860: `sfix_dut_fix.interpolate(Frequancy.from_f(fnew))`
Line 1864: `s2xthru.interpolate(Frequancy.from_f(fnew))`

Error Message: NameError: name 'Frequancy' is not defined

**Comment by jhillairet** [comment]
Thanks for reporting this bug @j0hu3ttl (and welcome!). Note even with the typo fixed, this new feature does not support yet non-uniform frequency vectors.

**Comment by jhillairet** [comment]
The release v0.22.1 corrects this bug.

@j0hu3ttl, note that you can use the `interpolate` method using a uniform frequency vector to make it work.
