### ISSUE TITLE
Connecting networks with complex port impedances gives incorrect results

### ISSUE THREAD

**Issue by Ttl** [scikit-rf/scikit-rf#654]
By default `Network` S-parameters are power waves, but connecting of networks is always calculated following `traveling` definition. If we generate two random two-port networks with Z-parameters we can calculate their cascade easily with ABCD parameters. We can also convert the Z-parameters to S-parameters assigning random complex port impedances and calculate the cascade network. The two methods should give the same resulting network and identical S-parameters when renormalized to the same port impedances but this is not the case with `power` and `pseudo` S-parameter definitions.

```python
import skrf
import numpy as np
np.random.seed(123)

freq = skrf.F(1,1,1)

# Generate random Z-parameters for two networks
z1 = np.random.uniform(1, 100, size=(1, 2, 2)) + 1j*np.random.uniform(-100, 100, size=(1, 2, 2))
z2 = np.random.uniform(1, 100, size=(1, 2, 2)) + 1j*np.random.uniform(-100, 100, size=(1, 2, 2))

# Port impedances
if 1:
    z0_1 = np.random.uniform(1, 100, size=2) + 1j*np.random.uniform(-100, 100, size=2)
    z0_2 = np.random.uniform(1, 100, size=2) + 1j*np.random.uniform(-100, 100, size=2)
    z0_3 = np.random.uniform(1, 100, size=2) + 1j*np.random.uniform(-100, 100, size=2)
else:
    # All S-parameters should be identical with only real port impedances
    z0_1 = 50
    z0_2 = 50
    z0_3 = 50

# Cascade Z-parameters calculated with ABCD parameters
net3_z = skrf.a2z(skrf.z2a(z1) @ skrf.z2a(z2))

for s_def in skrf.S_DEFINITIONS:
    print('s_def:', s_def)
    print('Cascade S-parameters calculated with Z and ABCD parameters:')
    # Initializing with z doesn't work
    net3_ref = skrf.Network(s=[[0,0],[0,0]], frequency=freq, z0=z0_3, s_def=s_def)
    net3_ref.z = net3_z
    print(net3_ref.s)

    net1 = skrf.Network(s=[[0,0],[0,0]], frequency=freq, z0=z0_1, s_def=s_def)
    net2 = skrf.Network(s=[[0,0],[0,0]], frequency=freq, z0=z0_2, s_def=s_def)
    net1.z = z1
    net2.z = z2

    print('Cascade calculated with S-parameters:')
    net12 = net1 ** net2
    net12.renormalize(z0_3, s_def=s_def)
    print(net12.s)
    print('Max error', np.max(np.abs(net12.s - net3_ref.s)))
    print()
```

```
s_def: power
Cascade S-parameters calculated with Z and ABCD parameters:
[[[-0.23391251+0.08191357j -0.11384683-0.17083815j]
  [ 0.24742266+0.06958025j  0.48164147+0.16554454j]]]
Cascade calculated with S-parameters:
[[[-0.15537994+0.18034563j -0.13194359-0.08436486j]
  [ 0.1941495 -0.02734986j  0.50599347+0.10007274j]]]
Max error 0.1259215466224455

s_def: pseudo
Cascade S-parameters calculated with Z and ABCD parameters:
[[[-0.20269054+0.55222866j -0.32239341-0.22958527j]
  [ 0.2010088 -0.18775523j  0.75449885+1.01992456j]]]
Cascade calculated with S-parameters:
[[[-0.20269054+0.55222866j -0.26726058-0.25330074j]
  [ 0.18583264-0.22994014j  0.75449885+1.01992456j]]]
Max error 0.060017105406647724

s_def: traveling
Cascade S-parameters calculated with Z and ABCD parameters:
[[[-0.20269054+0.55222866j -0.2827237 -0.08380469j]
  [ 0.33699066-0.15076128j  0.75449885+1.01992456j]]]
Cascade calculated with S-parameters:
[[[-0.20269054+0.55222866j -0.2827237 -0.08380469j]
  [ 0.33699066-0.15076128j  0.75449885+1.01992456j]]]
Max error 5.214799211354908e-16
```

For `pseudo` definition the bug can be fixed by changing the S-parameters in `impedance_mismatch` function (https://github.com/scikit-rf/scikit-rf/blob/master/skrf/network.py#L6576) to:
```python
n = npy.abs(z2/z1) * npy.sqrt(z1.real / z2.real)
result[:, 0, 0] = gamma
result[:, 1, 1] = -gamma
result[:, 1, 0] = 2 * z2 / (n * (z1 + z2))
result[:, 0, 1] = 2 * z1 * n / (z1 + z2)
```

For `power` I don't currently know how it should be fixed.

**Comment by jhillairet** [comment]
Well, to me it cannot be fixed for `power` case, as the power wave definition is inherently not made for complex characteristic impedances, as explained in:

R. B. Marks et D. F. Williams, [A general waveguide circuit theory](https://nvlpubs.nist.gov/nistpubs/jres/097/jresv97n5p533_A1b.pdf), J. RES. NATL. INST. STAN., vol. 97, nᵒ 5, p. 533, sept. 1992, doi: 10/gf3wcs.

D. Williams, [Traveling Waves and Power Waves: Building a Solid Foundation for Microwave Circuit Theory](https://www.nist.gov/system/files/documents/2017/05/09/MicrowaveCircuitTheory-proof.pdf), IEEE Microwave, vol. 14, n. 7, p. 38‑45, nov. 2013, doi: 10.1109/MMM.2013.2279494

By the way, using complex characteristic impedance in ANSYS Circuit leads to warnings, saying it only keep the real part of the char impedance. I guess it is the same in ADS?

**Comment by Ttl** [comment]
The obvious way to connect `power` networks is to convert to `pseudo`, connect and then convert back to `power`. But there should be some better way.

Related to the "Is it a bug?" tag, connecting two networks should result in the same network regardless of the representation that was used.

I'll try fixing this but it might take a while depending on how much of the existing tests depend on the current behavior.

**Comment by jhillairet** [comment]
> The obvious way to connect `power` networks is to convert to `pseudo`, connect and then convert back to `power`. But there should be some better way.
> 
> Related to the "Is it a bug?" tag, connecting two networks should result in the same network regardless of the representation that was used.

Well, I put the "I is it a bug?" tag as I'm still not convince this is a bug or feature: as the power-wave definition as not been forged to deal with complex characteristic impedances, instead of converting silently the S-parameter definition (which could have some side effects) the code may raise a warning or an error, don't you think?

**Comment by Ttl** [comment]
Powerwaves do work with complex impedances, it's just that they are not continuous across port interface unlike the other two definitions. It's the `traveling` definition that is questionable for complex port impedances as the derivation is made assuming real `z0`, however they do seem to give consistent results even with complex port impedances and I'm not quite sure what's the issue with them with complex ports. HFSS seems to renormalize complex port S-parameters with this definition.

Here are some real issues related to the S-parameter definition:

The default S-parameter definition for Network is `power`. This is set in `skrf.S_DEF_DEFAULT` and is set to `s_def` parameter in `Network` at initialization. However connection is not done according to powerwave definition and currently it follows `traveling` definition.

When making a `line` with a media the S-parameter matrix is created assuming that the reference impedance is the characteristic impedance of the media. If the port impedance should be something else thrus with that port impedance are connected to the line. Connection is again done with the `traveling` definition and thus the S-parameters of the network are actually `traveling`, however `s_def` is still set to default `power`.

`s_def` is important when converting to Z or Y parameters. For example S-parameter renormalization `network.renormalization` works by converting to Z and back to S. When trying to renormalize a line created from media it generates incorrect results as it reads the S-parameters as if they were powerwaves when they actually aren't. I mentioned the issue with renormalization in #651. Z-parameters are useful because they don't have port impedances like S-parameters and renormalizing S-parameters to new port impedances should give back the same Z-parameters as the network has not changed.

Another good paper about complex port S-parameters is:

S. Llorente-Romano, A. Garca-Lampérez, T. K. Sarkar and M. Salazar-Palma, [An Exposition on the Choice of the Proper S Parameters in Characterizing Devices Including Transmission Lines with Complex Reference Impedances and a General Methodology for Computing Them](https://ieeexplore.ieee.org/abstract/document/6645145), in IEEE Antennas and Propagation Magazine, vol. 55, no. 4, pp. 94-112, Aug. 2013.

**Comment by jhillairet** [comment]
OK, I understand the point and the issue.

I read this paper some years ago, but also found a kind of opposite view in: 
D. Williams, “Traveling waves and power waves: Building a solid foundation for microwave circuit theory,” IEEE Microwave Mag. 14, 38 (2013)

**Comment by rakeshsinha30** [comment]
For complex port impedance normalization of s parameters power wave is
best. As it is based on maximum power transfer theorem. The impedance
matching can easily explain using power wave. I have pointed it out in a
earlier discussion. The pseudo wave is problematic,  inconsistent with
conjunction matching.

**Comment by jhillairet** [comment]
> For complex port impedance normalization of s parameters power wave is best. As it is based on maximum power transfer theorem. The impedance matching can easily explain using power wave. I have pointed it out in a earlier discussion. The pseudo wave is problematic, inconsistent with conjunction matching.

Sure, but only because power waves have been made such as no reflection corresponds to maximum power transfer. However, physically, voltage waves are linear but power is not: in lossy lines, the net power flow is not in general the difference of the
forward and reflected power. There is an additional term which depends on the imaginary part of Z0 (see for ex https://ieeexplore.ieee.org/document/1448823)

And power-waves still lead to the caveat documented here:    
https://scikit-rf.readthedocs.io/en/latest/examples/networktheory/Working%20with%20Complex%20Characteristic%20Impedances.html

**Comment by jhillairet** [comment]
By the way, how did you stumble upon this bug? When i implemented both
power and pseudo waves, I've looked for realistic cases of use of complex
charac impedance but didn't find much..

**Comment by jhillairet** [comment]
> For complex port impedance normalization of s parameters power wave is best. As it is based on maximum power transfer theorem. The impedance matching can easily explain using power wave. I have pointed it out in a earlier discussion. The pseudo wave is problematic, inconsistent with conjunction matching.

I totally agree on that, and that's why it is the default behaviour in scikit-rf since #320, as it is more compatible with “common sense” I would say, and because power-wave formulation is used in (almost?) all commercial RF Circuit Simulators (S11=0 at conjugate matched condition). But this definition has still some caveats (like with Smith charts).

BTW, @Ttl (and @mhuser because it is related somewhat to the refactorings in progress), I found the following review quite nice (and freely available):

S. Amakawa, ‘Scattered Reflections on Scattering Parameters — Demystifying Complex-Referenced S Parameters —’, IEICE Trans. Electron., vol. E99.C, no. 10, pp. 1100–1112, 2016, doi: [10.1587/transele.E99.C.1100](https://doi.org/10.1587/transele.E99.C.1100).

It covers well the different cases where pseudo and power waves results differ. 

It also cites various situations where dealing with complex reference impedances is inevitable, such as after TRL calibrations or millimetre CMOS circuits.

**Comment by mhuser** [comment]
Great job !
