### ISSUE TITLE
Erroneous Demo in "Measuring a Mutiport Device with a 2-Port Network Analyzer"

### ISSUE THREAD

**Issue by biergaizi** [scikit-rf/scikit-rf#660]
In the tutorial *Measuring a Mutiport Device with a 2-Port Network Analyzer*, the section *[Test For Accuracy](https://scikit-rf.readthedocs.io/en/latest/examples/metrology/Measuring%20a%20Mutiport%20Device%20with%20a%202-Port%20Network%20Analyzer.html#Test-For-Accuracy)* appears erroneous, it has probably been broken by a regression.

Two years ago, this section reads:

> Making sure our composite network is the same as our DUT
>
>      [10]: composite == dut
>      [10]: True
>
> Nice!. How close ?
>
>      [11]: sum((composite - dut).s_mag)
>      [11]: 9.917536367984054e-13

But it now reads:

> Making sure our composite network is the same as our DUT
>
>      [10]: composite == dut
>      [10]: False
>
> Nice!. How close ?
>
>      [11]: sum((composite - dut).s_mag)
>      [11]: 880.7934663060666

**Comment by jhillairet** [comment]
Thank you for reporting. Indeed, seems less close ;)

**Comment by Ttl** [comment]
Looks like it broke in #448. Port numbering should probably be changed.
