### ISSUE TITLE
Circuits should not rely only on the network name to detect a port

### ISSUE THREAD

**Issue by luar123** [scikit-rf/scikit-rf#670]
To define a external port in circuits Circuit.Port() can be used and the docu states `Passing the frequency and name is mandatory. Port name must include the word ‘port’ inside. (ex: ‘Port1’ or ‘port_3’)`. Unfortunately all functions rely only on this string to determine if a network is a port or not, e.g. port_indexes():
```
if 'port' in str.lower(ntw.name):
                port_indexes.append(idx_cnx)
```
I use the circuit class to work with S-parameters from touchstone files and recently I loaded a file like `module123_sim_export.s123p` which led to a network.name containing 'port' and therefore the resulting circuit was completely wrong.

I think, using the network name as an identifier for ports is probably not a good idea at all, but I understand that it is a simple solution, because no additional parameter or similar is needed. If you want to keep it like this, maybe add some more metrics/restriction, e.g. only one-ports can be ports or the ports name has to start with `Port_`instead just containing `port`somewhere in the name.

**Comment by Ttl** [comment]
#671 should fix this by not using name to check if network is a port.

**Comment by jhillairet** [comment]
Indeed. When making the API, I had not imagined this scenario...

**Comment by luar123** [comment]
Awesome, thank you! That was fast :-)
