### ISSUE TITLE
Acknowledgement/Citation of skrf?

### ISSUE THREAD

**Issue by core-dd** [scikit-rf/scikit-rf#73]
Dear all,
as there was a lot of time invested into skrf over the last years, I'm wondering on how to acknowledge the beautiful work of all involved in an efficient manner in a scientific context. E.g. the Astropy community is going a way documented at [Astropy: About](http://www.astropy.org/about.html#acknowledge). Are there any opinions?

Cheers,
Jens

**Comment by arsenovic** [comment]
hey jens, 
   we dont have any technical article to cite for skrf (although andrew temme @temmeand  does have a draft for one which was never published.) 

i think adding  a section to the website indicated how to acknowledge skrf (like astropy) would be a good idea.  i can shell this out, and let others make comments/suggestions/PR's.

**Comment by arsenovic** [comment]
http://scikit-rf-web.readthedocs.io/about.html#

not a paper citation but here is a decent  blurb  about  references.
