### ISSUE TITLE
https://scikit-rf.readthedocs.io site is broken 

### ISSUE THREAD

**Issue by vishak-venkatraman** [scikit-rf/scikit-rf#774]
<img width="769" alt="image" src="https://user-images.githubusercontent.com/67716193/196723271-90e5c51e-8ed2-4aaa-90fe-e11fb1c603c7.png">

**Comment by FranzForstmayr** [comment]
I'll check later

**Comment by FranzForstmayr** [comment]
Hmm, I'm unable to reproduce locally...
And it's strange that no build error is shown:
https://readthedocs.org/api/v2/build/18384426.txt

**Comment by FranzForstmayr** [comment]
Opened a support ticket at readthedocs.org, hope I'll get an answer.

**Comment by FranzForstmayr** [comment]
Fixed with #775

**Comment by arsenovic** [comment]
fyi the calls the rf.styley() are causing errors in the docs still...

**Comment by FranzForstmayr** [comment]
Should be fixed with the next build too
