### ISSUE TITLE
API docs on ReadTheDocs not configured correctly

### ISSUE THREAD

**Issue by Vinc0110** [scikit-rf/scikit-rf#791]
The [API docs on RTD](https://scikit-rf.readthedocs.io/en/latest/api/generated/skrf.frequency.Frequency.html) are not right. The left columns are way too narrow:

![image](https://user-images.githubusercontent.com/63644854/200134155-06309743-d2e0-43aa-87ae-fb4db2038ae8.png)

**Comment by FranzForstmayr** [comment]
![image](https://user-images.githubusercontent.com/9936788/200584917-b4b357d9-12da-41c9-b504-5a568935ae0f.png)

Looks fine on my machine

**Comment by Vinc0110** [comment]
Believe it or not, it's also fine on my machine now...

**Comment by jhillairet** [comment]
> Believe it or not, it's also fine on my machine now...

I saw it too when you post the issue. I guess they have solved a problem on a server-side...
