### ISSUE TITLE
Calibration Example 4Port

### ISSUE THREAD

**Issue by Zwelckovich** [scikit-rf/scikit-rf#806]
Hello. is there a 4-Port calibration example for SOLT/TRL,etc. 
The only thing i have found in the docs was the 3 receiver example(https://scikit-rf.readthedocs.io/en/latest/examples/metrology/Calibration%20With%20Three%20Receivers.html)

Thanks and greetings
Sven

**Comment by jhillairet** [comment]
Not currently in the documentation. 

@arsenovic ?

**Comment by Zwelckovich** [comment]
Hi, any updates regarding the subject matter?

**Comment by Ttl** [comment]
There is currently no support for multiport calibration.

**Comment by arsenovic** [comment]
correct. but  i dont think it would be hard to do with what is already
there.

**Comment by Ttl** [comment]
Multi-port calibration is now implemented in #818. Documentation on how to use it: https://scikit-rf.readthedocs.io/en/latest/examples/metrology/Multi-port%20Calibration.html
