### ISSUE TITLE
Python 3.7 tests failing

### ISSUE THREAD

**Issue by Ttl** [scikit-rf/scikit-rf#819]
Flake8 dropped Python 3.7 support in November. Pip installs older version of flake8 with Python 3.7 support but it seems to be incompatible with `importlib_metadata` package version that pip installs and flake8 is unable to run. https://github.com/scikit-rf/scikit-rf/actions/runs/3791426085/jobs/6446846804

**Comment by jhillairet** [comment]
Cf.
https://github.com/python/importlib_metadata/issues/406
and
https://github.com/PyCQA/flake8/issues/1701
