### ISSUE TITLE
Import timestamp data while reading in a sNp file

### ISSUE THREAD

**Issue by mgoulder303** [scikit-rf/scikit-rf#884]
Most (if not all) *.sNp files generated from PNAs contain a timestamp in the header. It would be a great to import this timestamp into the Network object. I came across this as I have a large number of S-parameters I would like to plot over time. The filename does not have a timestamp but the file does in the header.

**Comment by jhillairet** [comment]
If the timestamp is in the comments in the header of the Touchstone file, it is available in the `.comments` property of the Network. Then it can be parsed to your need.

**Comment by cafeclimber** [comment]
On this, should comments be a `list[str]` instead of `str`? When constructing an mdif you pass a `list[str]` as comments. Might be easier to parse instead of one giant string blob

**Comment by jhillairet** [comment]
> On this, should comments be a `list[str]` instead of `str`? When constructing an mdif you pass a `list[str]` as comments. Might be easier to parse instead of one giant string blob

Yes eventually.

**Comment by mgoulder303** [comment]
> > On this, should comments be a `list[str]` instead of `str`? When constructing an mdif you pass a `list[str]` as comments. Might be easier to parse instead of one giant string blob
> 
> Yes eventually.

Good to know about the .comments property. Thanks.

As @cafeclimber mentioned, having a list[str] would be nice as a future feature.
