### ISSUE TITLE
"import skrf" fails 

### ISSUE THREAD

**Issue by jddmartin** [scikit-rf/scikit-rf#894]
import  skrf

fails with message:

_AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations_

after installation with "pip install scikit-rf"
on Ubuntu 20.04
Python 3.8
numpy version: 1.24.2

Same problem if I install via:
python3 -m pip install git+https://github.com/scikit-rf/scikit-rf

**Comment by FranzForstmayr** [comment]
Can you post the full stacktrace?

I don't think we forgot a `np.int` inside the codebase, but maybe there's an outdated 3rd party library which is imported in skrf.
This would be possible if you have an outdated optional dependency like `matplotlib`, as they aren't updated when installing `skrf` without the optional dependencies.

**Comment by jddmartin** [comment]
No problem.  Here is full session:

Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import skrf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jddmartin/.local/lib/python3.8/site-packages/skrf/__init__.py", line 25, in <module>
    from . import vectorFitting
  File "/home/jddmartin/.local/lib/python3.8/site-packages/skrf/vectorFitting.py", line 10, in <module>
    from . import plotting    # will perform the correct setup for matplotlib before it is called below
  File "/home/jddmartin/.local/lib/python3.8/site-packages/skrf/plotting.py", line 80, in <module>
    import networkx as nx
  File "/usr/lib/python3/dist-packages/networkx/__init__.py", line 115, in <module>
    import networkx.readwrite
  File "/usr/lib/python3/dist-packages/networkx/readwrite/__init__.py", line 15, in <module>
    from networkx.readwrite.graphml import *
  File "/usr/lib/python3/dist-packages/networkx/readwrite/graphml.py", line 314, in <module>
    class GraphML(object):
  File "/usr/lib/python3/dist-packages/networkx/readwrite/graphml.py", line 346, in GraphML
    (np.int, "int"), (np.int8, "int"),
  File "/home/jddmartin/.local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by FranzForstmayr** [comment]
It seems your `networkx` package is outdated.

Try `pip install scikit-rf[netw]` or `pip install --upgrade networkx`
