### ISSUE TITLE
Changing networks frequency directly results in wrong data 

### ISSUE THREAD

**Issue by vMeijin** [scikit-rf/scikit-rf#91]
The documentation of Network.f specifies, that the returned frequency is in Hz. However if the unit of the Network is not Hz, changing the .f property results in wrong frequency data. 
Example: 
```
import skrf
import numpy

n = 5
sp = numpy.ones((n, 2, 2))
frequency = numpy.linspace(0, 1, n)
z0 = 50 * numpy.ones(n)

nw = skrf.Network(f_unit="GHz")
nw.s, nw.f, nw.z0 = sp, frequency, z0

print(nw.f)
nw.f = nw.f
print(nw.f)

>> [  0.00000000e+00   2.50000000e+08   5.00000000e+08   7.50000000e+08
   1.00000000e+09]
>> [  0.00000000e+00   2.50000000e+17   5.00000000e+17   7.50000000e+17
   1.00000000e+18]
```
If .f always returns the data in Hz it also should accept only data in Hz.

**Comment by arsenovic** [comment]
yes this is correct. if you set/get `f` from the frequency property (ie `nw.frequency.f `) it works as you want 

the Network.f works differently which is misleading, and i think done for convenience. easy to change and probably makes sense to be consistent when reference the same property

**Comment by arsenovic** [comment]
6aad82354b539f3557800eabaa59015e2059b15d

**Comment by arsenovic** [comment]
so, it looks like a lot of tests rely on this feature through the network.__init__() function,  so i reverted it .  this will take more effort to fix all the tests.

**Comment by Ttl** [comment]
Head seems to be still broken. f.setter doesn't even set anything so most of the things are failing.

**Comment by arsenovic** [comment]
ok i look into this.

**Comment by arsenovic** [comment]
@tt i forgot to revert, it should be working now.

**Comment by alexpacini** [comment]
The commit is:
```python
self.frequency.f
```

why not
```python
self.frequency.f = f
```

I think the change was not setting the frequency at all.

**Comment by arsenovic** [comment]
hi,  
  i chose this because i used ghz most when i originally wrote this. perhaps a poor choice, but i think its not worth changing due to backwards compatability. i  also regret making the Network.f property, because it just a pointer to  the Network.frequency.f property. there should be only one.

**Comment by dkozel** [comment]
I think you should strongly consider putting these breaking changes on a roadmap for a future release. Simplicity of APIs and having "least surprise" defaults is worth folks having to add 'ghz' or 'frequency.' to a few lines of code after an update.
