### ISSUE TITLE
Unable to setup

### ISSUE THREAD

**Issue by Jackhub99** [scikit-rf/scikit-rf#942]
Hi, When i download it and try to setup it. It show some error and i think these error are general[.](capcuty.com)

**Comment by jhillairet** [comment]
Could you copy paste your error messages?

By the way, the recommended way to install scikit-rf is to use either
anaconda or pip.

**Comment by cafeclimber** [comment]
This seems like a spammy issue. The final period is a link to some video editing app. I think with the lack of response this can be closed
