### ISSUE TITLE
error on making exe with skrf lib

### ISSUE THREAD

**Issue by ouyiouchunbin** [scikit-rf/scikit-rf#946]
I was trying to make exe file with "pyinstllaer -Fw   .py", and when I execute the exe file, error massage was shown:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ty\\AppData\\Local\\Temp\\_MEI20602\\skrf\\data\\ntwk1.s2p'

Could you guys figure it out？

**Comment by cafeclimber** [comment]
Check out my project, [PyChamber](https://github.com/pychamber/pychamber) for a working PyInstaller .spec file. Let me know if you have any questions!

**Comment by jhillairet** [comment]
@ouyiouchunbin please reopen if you have further questions.
