### ISSUE TITLE
network_2_dataframe does not work for more than 10 ports

### ISSUE THREAD

**Issue by FranzForstmayr** [scikit-rf/scikit-rf#947]
Thank you for reporting a bug! To help us understanding the issue and how to reproduce it, please fill the following sections as best as you can.

**Describe the bug**
`network_2_dataframe` does not work for more than 10 ports

**To Reproduce**

```python
import skrf as rf

s = np.random.standard_normal((1, 11, 11))
f = [1]
netw = rf.Network(s=s, f=f)

s2 = netw.to_dataframe().values
assert s.size == s2.size
```

**Expected behavior**
`network_2_dataframe` should not drop data silently.

Issue behind is the column name creation in `skrf.io.general.network_2_dataframe` which result in the same column name S 111 for S (1,11) and S(11,1). Maybe we should add commas in the column name too, or use a different approach.

**Comment by cafeclimber** [comment]
Alot of SCPI stuff I've looked at uses underscores? E.g. S2_1, S11_1, S1_11, etc.
