### ISSUE TITLE
Probably a typo in time.py

### ISSUE THREAD

**Issue by pigskinsoup** [scikit-rf/scikit-rf#951]
Not 100% sure about this issue, because I'm not a coding person and didn't check the code. If someone can confirm with me about this small issue in the code would be wonderful.  Or correct me if I'm wrong.

**Describe the bug**
This typo is in the description of time-gating method fft. The description below indicated that data gets transformed into time-domain using inverse FFT and the time-domain signal is then transformed back into frequency-domain using inverse FFT too. Which probably a typo because transform into frequency-domain is using FFT right?

Below is the description about the fft method in time.py
        With *'fft'* (default), the data gets transformed into time-domain using inverse FFT and the gating is achieved
        by multiplication with the time-domain gate. The gated time-domain signal is then transformed back into
        frequency-domain using inverse FFT. As only positive signal frequencies are considered for the inverse FFT
        (with or without a dc component), the resulting time-domain signal has the same number of samples as in the
        frequency-domain, but is complex-valued. This method is also know as *time-domain band-pass mode*.

**Expected behavior**
just remove "inverse" in the process of time-domain transformed back into frequency-domain. If someone can confirm the code with me would be great. Or correct me if I'm wrong.

**Comment by Vinc0110** [comment]
Yes, you are right. We should fix this in the documentation. The code should be fine, though. Thanks for reporting!

**Comment by jhillairet** [comment]
> Yes, you are right. We should fix this in the documentation. The code should be fine, though. Thanks for reporting!

@Vinc0110 do you intend to fix the doc, or should I do it?

**Comment by Vinc0110** [comment]
Done. Thanks for the reminder ;)
