### ISSUE TITLE
VNA Control Documentation

### ISSUE THREAD

**Issue by jhillairet** [scikit-rf/scikit-rf#953]
**Describe the bug**
The VNA control example page generates errors (obviously). 

https://scikit-rf.readthedocs.io/en/latest/examples/instrumentcontrol/VNA%20Control.html

**Expected behavior**
Should the code be inert like in https://scikit-rf.readthedocs.io/en/latest/tutorials/VirtualInstruments.html ?

**Comment by cafeclimber** [comment]
Will fix asap
