### ISSUE TITLE
I am still seeing this issue : https://github.com/scikit-rf/scikit-rf/issues/207 

### ISSUE THREAD

**Issue by JG1968** [scikit-rf/scikit-rf#960]
Thank you for reporting a bug! To help us understanding the issue and how to reproduce it, please fill the following sections as best as you can.

**Describe the bug**
I am using skit rf 0.29.0 in vs code. I am experiencing this old issue https://github.com/scikit-rf/scikit-rf/issues/207 again. What am I doing wrong.
**To Reproduce**

plot_s.d_time produces x axis is in Frequency in time domain plot

**Data**
If applicable, add the data leading to the issue (a minimum example is appreciated)

**Screenshots**
![image](https://github.com/scikit-rf/scikit-rf/assets/145983966/b0d835d1-8e96-42da-b331-74803b1b7ef2)

**System**
 - OS: windows10
 - scikit-rf version 0.29.0

**Additional context**
Add any other context about the problem here if relevant.

**Comment by FranzForstmayr** [comment]
Obviously regression after #848. Will try to fix that again!

**Comment by JG1968** [comment]
Thanks a lot. Really appreciate your work.
