### ISSUE TITLE
How to release Network object ? 

### ISSUE THREAD

**Issue by svandenb-dev** [scikit-rf/scikit-rf#973]
When we instantiate Network class with loading touchstone file, what is the best way to release memory ?
I can't find method like close() or release()

**Comment by jhillairet** [comment]
You don't need any close method to close the Touchstone files (it should be done automatically). If you need to delete a Network object, you can delete it (`del` keyword).

Are you affected by memory problems while using scikit-rf ? If yes, could you describe your problem ?

**Comment by jhillairet** [comment]
@svandenb-dev , could you describe more your issue?
