### ISSUE TITLE
scikit-rf port to .Net C#. Help Needed!

### ISSUE THREAD

**Issue by Zinc999** [scikit-rf/scikit-rf#980]
Hi ,

I have a UseCase where I would like to use scikit-rf functionality but... python is not allowed on the system. 

Hence, looking out for any ongoing effort where sckit-rf port to .Net C# is planned or ongoing.

If not, I would like to do that. To get started I have following queries:
1. Is it legally okay to start a port?
2. If yes then can we create a repo here under scikit-rf umbrella?
3. If yes for the above, then who all are interested in helping me :)

Looking out for some helping hands. Thanks in advance!

**Comment by arsenovic** [comment]
just tell chatgpt to do it.

**Comment by jhillairet** [comment]
I'm closing for now, as a port in C# is not foreseen. Anyway, anybody can use the code in this repo for making a C# version of scikit-rf.
