### ISSUE TITLE
Google Group "scikit-rf" still exists and is full of spam

### ISSUE THREAD

**Issue by cweickhmann** [scikit-rf/scikit-rf#981]
I just noticed that the Google group "scikit-rf@googlegroups.com" still exists. Of course it is full of spam. If anyone still has access, it would be great if it could be closed down.

**Comment by jhillairet** [comment]
@arsenovic , can you look?

**Comment by arsenovic** [comment]
Sure !On Nov 30, 2023, at 4:07 PM, Julien Hillairet ***@***.***> wrote:﻿
@arsenovic , can you look?

**Comment by Vinc0110** [comment]
Looks like the mailing list is gone now.
